#!/usr/bin/env bash
# cloud-build-fresh-slot.sh — auto-create a fresh subdir per /super dispatch
#
# Why: Cloud Build's lock is per (enrolled_fp_hash × project_slug). Same
# fingerprint + same project_slug = SAME box slot. To get parallel boxes
# (or to escape a stale lock), use a different directory each time.
#
# Usage:
#   bash ~/.claude/hooks/cloud-build-fresh-slot.sh [plan_rel] [branch] [task_label]
#
# Behavior:
#   1. Creates a fresh subdirectory under CWD/.cb-runs/<timestamp>-<branch>/
#   2. Sets up orphan-snapshot: README + plan + .claude/plans/ + hermetic flag
#   3. Inits git + creates private/<branch> branch
#   4. Pushes to a new GitHub repo (named after the fresh subdir)
#   5. Dispatches via cloud-build-super-dispatch.sh
#   6. Polls until state=done OR state=failed
#   7. Lands the result + prints final summary
#
# This gives every /super call a UNIQUE project_slug → UNIQUE box slot,
# so multiple /super calls in parallel don't block each other on the bastion.

set -uo pipefail

# Args
PLAN_REL="${1:-.claude/plans/plan.md}"
BR="${2:-$(git -C "$PWD" branch --show-current 2>/dev/null || echo main)}"
TASK_LABEL="${3:-cloud-build}"

# Compute fresh slot dir
TIMESTAMP="$(date +%Y%m%d-%H%M%S)-$RANDOM"
ORIG_BASENAME="$(basename "$PWD")"
SLOT_NAME="${ORIG_BASENAME}-${BR//\//-}-${TIMESTAMP}"
SLOT_DIR="$HOME/.cb-runs/$SLOT_NAME"

# Ensure CWD is a git repo (or init if needed)
if ! git -C "$PWD" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "FATAL: CWD is not a git repo: $PWD" >&2
  exit 1
fi

# Create the slot dir
mkdir -p "$SLOT_DIR"
cd "$SLOT_DIR"

# Init fresh git
git init -q
git config user.email "supervisor@cloud-build.local"
git config user.name "Cloud Build"
git branch -M main

# Archive the original repo's HEAD into the slot dir
git -C "$OLDPWD" archive --format=tar HEAD | tar -x

# Prune heavy directories that the box doesn't need
rm -rf evidence/ docs/ screenshots/ roadmap/ world_reference/ .beads/ testing_ui/ testing_mcp/

# Set up plan + hermetic
mkdir -p .claude/plans
if [ -f "$OLDPWD/$PLAN_REL" ]; then
  cp "$OLDPWD/$PLAN_REL" .claude/plans/plan.md
else
  cat > .claude/plans/plan.md <<EOF
# $TASK_LABEL

## Goal
Generated by cloud-build-fresh-slot.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
fi
touch .claude/cloud-build-hermetic-confirmed

# Initial commit + branch
cat > README.md <<EOF
# $SLOT_NAME

Slot for /super dispatch from $OLDPWD on branch $BR at $(date -u).
Project slug: $(basename $SLOT_DIR)
EOF
git add -A
git commit -q -m "snapshot: $TASK_LABEL orphan for cloud-build dispatch proof"

# Create + push to fresh GitHub repo
REPO_NAME="$(echo $SLOT_NAME | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-')"
gh api -X POST /user/repos -f name="$REPO_NAME" -F private=true >/dev/null 2>&1
git remote add origin "https://github.com/$(gh api user --jq .login)/$REPO_NAME.git"
git push -u origin HEAD:main 2>&1 | tail -1

# Create the work branch
git checkout -q -b "private/$BR"
git push -u origin "private/$BR" 2>&1 | tail -1

# Dispatch
BRANCH=$(git branch --show-current)
SHA=$(git rev-parse HEAD)
CLOUD_HERMETIC_CONFIRMED=1 bash ~/superpowers-cloud-build-main/skills/cloud-build/scripts/cloud-build-super-dispatch.sh \
    "$PWD" ".claude/plans/plan.md" "$BRANCH" "$SHA" 2>&1 | tail -10

# Save the slot dir for status polling
echo "$SLOT_DIR" > /tmp/cb-current-slot-dir.txt

# Poll for completion
echo "=== polling for completion (up to 10 min) ==="
for i in $(seq 1 20); do
  sleep 30
  STATUS_JSON=$(timeout 30 bash ~/superpowers-cloud-build-main/skills/cloud-build/scripts/lib-client.sh cloud_build_fetch_status "$PWD" 2>&1; timeout 5 git show cloud/status:status.json 2>/dev/null)
  STATE=$(echo "$STATUS_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin).get('state',''))" 2>/dev/null)
  HEAD=$(echo "$STATUS_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin).get('head_sha','')[:10])" 2>/dev/null)
  TASK=$(echo "$STATUS_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin).get('current_task','')[:40])" 2>/dev/null)
  echo "  [$((i*30))s] state=$STATE head=$HEAD task=$TASK"
  if [ "$STATE" = "done" ] || [ "$STATE" = "failed" ]; then break; fi
done

# Land
if [ "$STATE" = "done" ]; then
  RUN_ID=$(timeout 5 git show cloud/status:status.json | python3 -c "import json,sys; print(json.load(sys.stdin)['run_id'])")
  echo "=== landing $RUN_ID ==="
  bash ~/superpowers-cloud-build-main/skills/cloud-build/scripts/lib-client.sh cloud_build_land_result \
      "$PWD" "$BRANCH" "$HEAD" "$RUN_ID" 2>&1 | head -3
  echo "---"
  git log --format="%h %an %s" -3 | head -5
fi

echo ""
echo "=== /super done ==="
echo "Slot dir: $SLOT_DIR"
echo "GitHub repo: $REPO_NAME"
echo "Work branch: $BRANCH"
echo "Final state: $STATE"
