#\!/bin/bash
# 🚀 Claude Commands Installation Script
# Auto-generated by /exportcommands

set -e  # Exit on any error

echo "🚀 Installing Claude Commands..."
echo "=================================="

# Check if we're in a git repository and navigate to root
if \! git_root=$(git rev-parse --show-toplevel 2>/dev/null); then
    echo "❌ Error: Not inside a git repository" >&2
    exit 1
fi
cd "$git_root"

# Create .claude/commands directory if it doesn't exist
if [ \! -d ".claude" ]; then
    echo "📁 Creating .claude directory..."
    mkdir -p .claude
fi

if [ \! -d ".claude/commands" ]; then
    echo "📁 Creating .claude/commands directory..."
    mkdir -p .claude/commands
fi

# Create .claude/hooks directory if it doesn't exist
if [ \! -d ".claude/hooks" ]; then
    echo "📁 Creating .claude/hooks directory..."
    mkdir -p .claude/hooks
fi

# Copy commands from exported commands/ to .claude/commands/
echo "📋 Installing command definitions..."
if [ -d "commands" ]; then
    for file in commands/*; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            # Skip README files - they belong in the repository root
            if [[ "$filename" == "README"* ]]; then
                echo "   ⏭ Skipping $filename (documentation file)"
                continue
            fi
            echo "   • $filename"
            cp "$file" ".claude/commands/$filename"
        fi
    done
    echo "✅ Commands installed to .claude/commands/"
else
    echo "⚠️  Warning: commands/ directory not found"
fi

# Copy hooks from exported hooks/ to .claude/hooks/ (with subdirectory support)
echo "📎 Installing Claude Code hooks..."
if [ -d "hooks" ]; then
    find hooks -type f \( -name "*.sh" -o -name "*.py" -o -name "*.md" \) -print0 | while IFS= read -r -d '' hook_file; do
        relative_path="${hook_file#hooks/}"
        target_path=".claude/hooks/$relative_path"
        target_dir=$(dirname "$target_path")
        
        # Create target directory if needed
        mkdir -p "$target_dir"
        
        echo "   📎 $relative_path"
        cp "$hook_file" "$target_path"
        
        # Ensure executables keep their bit
        case "$relative_path" in
            *.sh|*.py) chmod +x "$target_path" ;;
        esac
    done
    echo "✅ Hooks installed to .claude/hooks/"
else
    echo "⚠️  Warning: hooks/ directory not found"
fi

# Copy claude_start.sh from infrastructure-scripts to root
echo "🚀 Installing startup script..."
if [ -f "infrastructure-scripts/claude_start.sh" ]; then
    echo "   • claude_start.sh"
    cp "infrastructure-scripts/claude_start.sh" "./claude_start.sh"
    chmod +x "./claude_start.sh"
    echo "✅ Startup script installed to root directory"
else
    echo "⚠️  Warning: claude_start.sh not found in infrastructure-scripts/"
fi

# Update .gitignore with copied files
echo "📝 Updating .gitignore..."

# Function to add gitignore entries atomically and prevent duplicates
add_to_gitignore() {
    local entry="$1"
    local comment="$2"

    if \! grep -Fq "^$comment" .gitignore 2>/dev/null; then
        echo "" >> .gitignore
        echo "$comment" >> .gitignore
        echo "$entry" >> .gitignore
        return 0
    fi
    return 1
}

# Check and add entries only if needed
entries_added=false

if add_to_gitignore ".claude/" "# Claude Commands - Auto-installed by install.sh"; then
    entries_added=true
fi

if add_to_gitignore "claude_start.sh" "# Claude startup script - Auto-installed"; then
    entries_added=true
fi

if [ "$entries_added" = true ]; then
    echo "✅ Updated .gitignore with installed files"
else
    echo "✅ .gitignore already contains necessary entries"
fi

echo ""
echo "🎉 Installation Complete\!"
echo ""
echo "Next steps:"
echo "1. Adapt commands for your project (replace \$PROJECT_ROOT placeholders)"
echo "2. Update claude_start.sh with your project-specific paths"
echo "3. Run ./claude_start.sh to start Claude Code with MCP servers"
echo ""
echo "⚠️  Remember: These are reference commands that may need project-specific adaptation"
