#!/bin/bash
# Claude Commands Installation Script
# Auto-generated by /exportcommands

set -e  # Exit on any error

echo "🚀 Installing Claude Commands..."
echo "=================================="

# Check if we're in a git repository and navigate to root
if ! git_root=$(git rev-parse --show-toplevel 2>/dev/null); then
    echo "❌ Error: Not inside a git repository" >&2
    exit 1
fi
cd "$git_root"

# Create .claude/commands directory if it doesn't exist
if [ ! -d ".claude" ]; then
    echo "📁 Creating .claude directory..."
    mkdir -p .claude
fi

if [ ! -d ".claude/commands" ]; then
    echo "📁 Creating .claude/commands directory..."
    mkdir -p .claude/commands
fi

# Copy commands from exported commands/ to .claude/commands/
echo "📋 Installing command definitions..."
if [ -d "commands" ]; then
    for file in commands/*; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            # Skip README files - they belong in the repository root
            if [[ "$filename" == "README"* ]]; then
                echo "   ⏭ Skipping $filename (documentation file)"
                continue
            fi
            echo "   • $filename"
            cp "$file" ".claude/commands/$filename"
        fi
    done
    echo "✅ Commands installed to .claude/commands/"
else
    echo "⚠️  Warning: commands/ directory not found"
fi

# Copy claude_start.sh from infrastructure-scripts to root
echo "🚀 Installing startup script..."
if [ -f "infrastructure-scripts/claude_start.sh" ]; then
    echo "   • claude_start.sh"
    cp "infrastructure-scripts/claude_start.sh" "./claude_start.sh"
    chmod +x "./claude_start.sh"
    echo "✅ Startup script installed to root directory"
else
    echo "⚠️  Warning: claude_start.sh not found in infrastructure-scripts/"
fi

# Update .gitignore with copied files
echo "📝 Updating .gitignore..."
gitignore_entries=""

# Check if entries need to be added and build gitignore content
claude_commands_missing=false
claude_start_missing=false

if ! grep -q "^# Claude Commands - Auto-installed by install.sh" .gitignore 2>/dev/null; then
    claude_commands_missing=true
fi

if ! grep -q "^claude_start.sh" .gitignore 2>/dev/null; then
    claude_start_missing=true
fi

# Build gitignore entries only if needed
if [ "$claude_commands_missing" = true ] || [ "$claude_start_missing" = true ]; then
    if [ "$claude_commands_missing" = true ]; then
        gitignore_entries+="
# Claude Commands - Auto-installed by install.sh
.claude/
.claude/commands/
"
    fi

    if [ "$claude_start_missing" = true ]; then
        gitignore_entries+="
# Claude startup script - Auto-installed
claude_start.sh
"
    fi
    echo "$gitignore_entries" >> .gitignore
    echo "✅ Updated .gitignore with installed files"
else
    echo "✅ .gitignore already contains necessary entries"
fi

echo ""
echo "🎉 Installation Complete!"
echo ""
echo "Next steps:"
echo "1. Adapt commands for your project (replace \$PROJECT_ROOT placeholders)"
echo "2. Update claude_start.sh with your project-specific paths"
echo "3. Run ./claude_start.sh to start Claude Code with MCP servers"
echo ""
echo "⚠️  Remember: These are reference commands that may need project-specific adaptation"