#\!/bin/bash
# Claude Commands Installation Script
# Auto-generated by /exportcommands

set -e  # Exit on any error

echo "🚀 Installing Claude Commands..."
echo "=================================="

# Check if we're in a git repository and navigate to root
if \! git_root=$(git rev-parse --show-toplevel 2>/dev/null); then
    echo "❌ Error: Not inside a git repository" >&2
    exit 1
fi
cd "$git_root"

# Create .claude/commands directory if it doesn't exist
if [ \! -d ".claude" ]; then
    echo "📁 Creating .claude directory..."
    mkdir -p .claude
fi

if [ \! -d ".claude/commands" ]; then
    echo "📁 Creating .claude/commands directory..."
    mkdir -p .claude/commands
fi

# Copy commands from exported commands/ to .claude/commands/
echo "📋 Installing command definitions..."
if [ -d "commands" ]; then
    for file in commands/*; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            # Skip README files - they belong in the repository root
            if [[ "$filename" == "README"* ]]; then
                echo "   ⏭ Skipping $filename (documentation file)"
                continue
            fi
            echo "   • $filename"
            cp "$file" ".claude/commands/$filename"
        fi
    done
    echo "✅ Commands installed to .claude/commands/"
else
    echo "⚠️  Warning: commands/ directory not found"
fi

# Update .gitignore with copied files
echo "📝 Updating .gitignore..."

# Function to add gitignore entries atomically and prevent duplicates
add_to_gitignore() {
    local entry="$1"
    local comment="$2"
    
    if \! grep -Fq "^$comment" .gitignore 2>/dev/null; then
        echo "" >> .gitignore
        echo "$comment" >> .gitignore
        echo "$entry" >> .gitignore
        return 0
    fi
    return 1
}

# Check and add entries only if needed
entries_added=false

if add_to_gitignore ".claude/" "# Claude Commands - Auto-installed by install.sh"; then
    entries_added=true
fi

if [ "$entries_added" = true ]; then
    echo "✅ Updated .gitignore with installed files"
else
    echo "✅ .gitignore already contains necessary entries"
fi

echo ""
echo "🎉 Installation Complete\!"
echo ""
echo "Next steps:"
echo "1. Adapt commands for your project (replace \$PROJECT_ROOT placeholders)"
echo "2. Run commands like /execute, /pr, /copilot to experience the composition system"
echo "3. Explore the Command Deep Dive section in README.md for detailed explanations"
echo ""
echo "⚠️  Remember: These are reference commands that may need project-specific adaptation"
