#!/usr/bin/env python3
"""
Test for recursive meta-comment bug in commentfetch
Demonstrates red-green methodology with exact bug reproduction
"""

import unittest
from unittest.mock import patch, MagicMock
import sys
import os

# Add the module path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '.claude', 'commands', '_copilot_modules'))

from commentfetch import CommentFetch


class TestCommentFetchRecursiveBug(unittest.TestCase):
    """Test cases for recursive meta-comment bug"""

    def setUp(self):
        """Set up test fixtures"""
        self.pr_number = "1510"
        self.fetcher = CommentFetch(self.pr_number)

    def test_regression_recursive_meta_comments_marked_as_requiring_response(self):
        """
        RED: This test should FAIL initially - reproducing the exact bug

        Bug: Meta-comments with "CLAUDE RESPONSE NEEDED" should NOT be marked
        as requiring responses to prevent infinite recursion.
        """
        # Simulate a meta-comment generated by commentreply.py
        meta_comment = {
            "id": 12345,
            "body": """🚨 **CLAUDE RESPONSE NEEDED** (Commit: abc123)

Comment #67890 by @coderabbitai:
> Using f-string with json.dumps() output in shell command is unsafe...

❌ No Claude-generated response found for this comment.
✅ Claude should analyze this comment and add response to responses.json

**Required**: Claude must read comment content, implement any necessary fixes, and generate appropriate technical response.""",
            "user": {"login": "jleechan2015"},
            "created_at": "2025-09-02T01:00:00Z"
        }

        # BUG: This should return False but currently returns True
        result = self.fetcher._requires_response(meta_comment)

        # This assertion will FAIL in RED phase (bug present), PASS in GREEN phase (bug fixed)
        self.assertFalse(result,
                        "Meta-comments should NOT require responses to prevent recursive processing")

    def test_regression_actual_technical_comments_still_require_response(self):
        """
        Ensure the fix doesn't break legitimate technical comments
        """
        # Simulate an actual CodeRabbit technical comment
        technical_comment = {
            "id": 67890,
            "body": "Using f-string with `json.dumps()` output in shell command is unsafe due to potential shell injection. Consider using a more secure approach.",
            "user": {"login": "coderabbitai"},
            "created_at": "2025-09-02T00:30:00Z"
        }

        result = self.fetcher._requires_response(technical_comment)

        # This should always be True for actual technical comments
        self.assertTrue(result,
                       "Legitimate technical comments should still require responses")

    def test_regression_quote_only_comments_filtered_out(self):
        """
        Test that simple quote-only comments don't require responses
        """
        quote_comment = {
            "id": 11111,
            "body": "> Seems like the humans are having a chat.",
            "user": {"login": "someuser"},
            "created_at": "2025-09-02T01:15:00Z"
        }

        # BUG: This should return False but currently returns True
        result = self.fetcher._requires_response(quote_comment)

        self.assertFalse(result,
                        "Simple quote-only comments should not require responses")


if __name__ == "__main__":
    unittest.main()
