#!/bin/bash
# List command - Show all available Claude commands
# Usage: ./list.sh

echo "=== Available Claude Commands for Cursor ==="
echo ""
echo "Git & Workflow Commands:"
echo "  header.sh         - Generate git branch header"
echo "  nb.sh            - Create new branch from main (alias: newbranch.sh)"
echo "  integrate.sh     - Fresh branch from main with cleanup"
echo "  push.sh          - Validate and push changes with PR update"
echo "  pr.sh           - Create pull request with validation"
echo ""
echo "Testing Commands:"
echo "  test.sh          - Run full test suite + CI check"
echo "  testui.sh        - Browser UI tests (mock APIs)"
echo "  testuif.sh       - Browser UI tests (REAL APIs - costs $)"
echo "  testhttp.sh      - HTTP API tests (mock)"
echo "  testi.sh         - Integration tests"
echo "  coverage.sh      - Generate test coverage report"
echo ""
echo "Development Commands:"
echo "  tdd.sh           - Test-Driven Development guide"
echo "  rg.sh           - Red-Green testing methodology"
echo "  context.sh       - Show current project context"
echo "  learn.sh         - Document learnings"
echo ""
echo "AI-Assisted Commands:"
echo "  think.sh         - Sequential thinking guide"
echo "  execute.sh       - Task execution checklist (aliases: e.sh, plan.sh)"
echo ""
echo "Utility:"
echo "  list.sh          - This help message"
echo "  setup-aliases.sh - Setup command aliases (source it)"
echo ""
echo "For detailed help on any command, see export.md or README.md"
echo "Most commands support -h or --help for usage info"