#!/bin/bash
# TDD command - Test-Driven Development workflow guide
# Usage: ./tdd.sh

echo "=== Test-Driven Development (TDD) Workflow ==="
echo ""
echo "TDD Red-Green-Refactor Cycle:"
echo ""
echo "1. RED: Write a failing test first"
echo "   - Define expected behavior"
echo "   - Run test to confirm it fails"
echo ""
echo "2. GREEN: Write minimal code to pass"
echo "   - Implement just enough to make test pass"
echo "   - Run test to confirm it passes"
echo ""
echo "3. REFACTOR: Improve the code"
echo "   - Clean up implementation"
echo "   - Ensure tests still pass"
echo ""
echo "Example workflow:"
echo "$ # 1. Create test file"
echo "$ echo 'def test_new_feature(): assert feature() == expected' > test_feature.py"
echo "$ python -m pytest test_feature.py  # Should fail (RED)"
echo "$ # 2. Implement feature"
echo "$ echo 'def feature(): return expected' > feature.py"
echo "$ python -m pytest test_feature.py  # Should pass (GREEN)"
echo "$ # 3. Refactor as needed"
echo ""
echo "Benefits:"
echo "- Tests document expected behavior"
echo "- Confidence in refactoring"
echo "- Better code design"
echo "- Regression prevention"
echo ""
echo "Start your TDD cycle now!"