#!/usr/bin/env bash
# exportcommands.sh — Export ~/.claude/ dirs to jleechanorg/claude-commands
#
# Behavior:
#   - Source files overwrite target files (rsync default)
#   - Files only in target are PRESERVED (rsync default; no --delete flag)
#   - README.md is regenerated by Claude CLI
#   - Content filters strip project-specific strings via perl -pi -e (supports \b on macOS)
#
# Usage: bash ~/.claude/commands/exportcommands.sh [--dry-run]

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────────────
TARGET_REPO="jleechanorg/claude-commands"
BRANCH="export-$(date +%Y%m%d-%H%M%S)"
REPO_DIR="$(mktemp -d)/claude-commands"

# ── Cleanup trap — remove temp dir on exit (normal or error) ────────────────
trap 'rm -rf "$(dirname "$REPO_DIR")"' EXIT
GLOBAL_CLAUDE="$HOME/.claude"
# Detect project root: honour $PROJECT_ROOT env var, then git root of current dir.
# Fail fast if git rev-parse fails — do not silently export to a bogus path.
if [[ -z "${PROJECT_ROOT:-}" ]]; then
  PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
    echo "ERROR: PROJECT_ROOT is unset and git rev-parse failed. Set PROJECT_ROOT before running." >&2
    exit 1
  }
fi
PROJECT_CLAUDE="$PROJECT_ROOT/.claude"

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# Dirs from ~/.claude/ → .claude/<dir> in target repo
CLAUDE_DIRS=(commands skills hooks agents scripts)

# Dirs from project root → repo root in target repo
ROOT_DIRS=(orchestration automation ralph)

# Files to exclude from content filtering (contain literal regex patterns or are test files
# that assert on the source strings and must not have them silently replaced)
FILTER_SKIP=(exportcommands.py exportcommands.sh loc_simple.sh test_exportcommands.py)

# Content filter substitutions (applied to all .md .py .sh .yml files)
# NOTE: Uses perl -pi -e for cross-platform \b word-boundary support (macOS sed lacks it)
# IMPORTANT: Specific patterns must come before general ones:
#   jleechanorg/worldarchitect.ai BEFORE worldarchitect.ai (general would consume specific)
declare -a SUBS=(
  's|jleechanorg/worldarchitect\.ai|\$GITHUB_REPOSITORY|g'
  's|worldarchitect\.ai|your-project.com|g'
  's|worldarchitect-ci|\$\{PROJECT_NAME:-your-project\}-ci|g'
  's|/Users/jleechan|\$HOME|g'
  's|\bjleechan\b|\$USER|g'
  's|jleechantest\@gmail\.com|<your-email\@gmail.com>|g'
  's|WorldArchitect\.AI|Your Project|g'
  's|TESTING=true vpython|TESTING=true python|g'
)
# mvp_site/ substitution is applied separately, skipping workflow files.
# GitHub Actions does NOT expand $PROJECT_ROOT in paths: filters or hashFiles().
MVp_SITE_SUB='s|mvp_site/|\$PROJECT_ROOT/|g'

# ── Helpers ─────────────────────────────────────────────────────────────────
log()  { echo "  $*"; }
ok()   { echo "  ✅ $*"; }
warn() { echo "  ⚠️  $*" >&2; }

apply_filters() {
  local file="$1"
  local base; base="$(basename "$file")"
  for skip in "${FILTER_SKIP[@]}"; do
    [[ "$base" == "$skip" ]] && return 0
  done
  # Use perl -pi -e: supports \b word boundaries on macOS (BSD sed lacks \b)
  for sub in "${SUBS[@]}"; do
    perl -pi -e "$sub" "$file"
  done
  # Apply mvp_site/ → $PROJECT_ROOT/ only for non-workflow files.
  # GitHub Actions does NOT expand $PROJECT_ROOT in `paths:` filters or hashFiles(),
  # so substituting it into workflows/*.yml would silently break CI triggers.
  case "$file" in
    workflows/*.yml|workflows/*.yaml) ;;
    *) perl -pi -e "$MVp_SITE_SUB" "$file" ;;
  esac
}

# ── Clone & branch ──────────────────────────────────────────────────────────
echo "▶ Cloning $TARGET_REPO..."
gh repo clone "$TARGET_REPO" "$REPO_DIR"
cd "$REPO_DIR"

git config user.email "claude-export@anthropic.com"
git config user.name "Claude Export"
git config commit.gpgsign false

git checkout main
git pull --ff-only origin main
git checkout -b "$BRANCH"

# ── Union-merge ~/.claude/ and .claude/ into export ──────────────────────────
# Strategy:
#   - File only in GLOBAL (~/.claude/):   use global   (came from another project/plugin)
#   - File only in PROJECT (.claude/):    use project  (worldai source)
#   - File in both, identical:            use either   (no conflict)
#   - File in both, project newer:        use project  (auto-resolve)
#   - File in both, global newer:         use global   (auto-resolve)
#   - File in both, same mtime, differ:   CONFLICT — report and use project as tiebreak
#
CONFLICTS=()   # accumulates "dir/relpath: reason" strings for any unresolved conflicts

union_dir() {
  local dir="$1"
  local global_src="$GLOBAL_CLAUDE/$dir"
  local project_src="$PROJECT_CLAUDE/$dir"
  local dst=".claude/$dir"
  mkdir -p "$dst"

  # Collect union of all relative paths from both sources
  local all_relpaths=()
  while IFS= read -r -d '' f; do
    all_relpaths+=("${f#$global_src/}")
  done < <(find "$global_src" -type f \
    \( -not -name '*.pyc' \) \
    \( -not -name '*.pyo' \) \
    \( -not -name '.DS_Store' \) \
    \( -not -path '*/__pycache__/*' \) \
    \( -not -path '*/.ruff_cache/*' \) \
    \( -not -path '*/canvas-fonts/*' \) \
    \( -not -name '*.ttf' \) \
    \( -not -name '*.otf' \) \
    \( -not -name '*.woff' \) \
    \( -not -name '*.woff2' \) \
    \( -not -name '*.eot' \) \
    \( -not -name '*.png' \) \
    \( -not -name '*.jpg' \) \
    \( -not -name '*.jpeg' \) \
    \( -not -name '*.gif' \) \
    \( -not -name '*.ico' \) \
    \( -not -name '*.webp' \) \
    \( -not -name '*.svg' \) \
    \( -not -name '*.mp4' \) \
    \( -not -name '*.mp3' \) \
    \( -not -name '*.wav' \) \
    \( -not -name '*.pdf' \) \
    \( -not -name '*.zip' \) \
    \( -not -name '*.tar' \) \
    \( -not -name '*.gz' \) \
    \( -not -name '*.db' \) \
    \( -not -name '*.sqlite' \) \
    \( -not -name '*.sqlite3' \) \
    \( -not -name '*.xsd' \) \
    \( -not -name '*.xml' \) \
    \( -not -name '*.testmondata' \) \
    -print0 2>/dev/null || true)

  while IFS= read -r -d '' f; do
    local relpath="${f#$project_src/}"
    # Only add if not already in the list
    local already=false
    for r in "${all_relpaths[@]:-}"; do [[ "$r" == "$relpath" ]] && already=true && break; done
    $already || all_relpaths+=("$relpath")
  done < <(find "$project_src" -type f \
    \( -not -name '*.pyc' \) \
    \( -not -name '.DS_Store' \) \
    \( -not -path '*/__pycache__/*' \) \
    \( -not -path '*/.ruff_cache/*' \) \
    \( -not -path '*/canvas-fonts/*' \) \
    -not -name 'exportcommands.py' \
    \( -name '*.sh' -o -name '*.py' -o -name '*.md' -o -name '*.json' \
       -o -name '*.toml' -o -name '*.yaml' -o -name '*.yml' \
       -o -name '*.js' -o -name '*.ts' -o -name '*.css' -o -name '*.html' \
       -o -name '*.cfg' -o -name '*.ini' -o -name '*.conf' \) \
    -print0 2>/dev/null || true)

  local only_global=0 only_project=0 identical=0 auto_resolved=0

  for relpath in "${all_relpaths[@]:-}"; do
    [[ -z "$relpath" ]] && continue
    local gfile="$global_src/$relpath"
    local pfile="$project_src/$relpath"
    local outfile="$dst/$relpath"
    mkdir -p "$(dirname "$outfile")"

    if [[ ! -f "$gfile" ]]; then
      # Only in project → use project
      cp "$pfile" "$outfile"
      only_project=$((only_project + 1))
    elif [[ ! -f "$pfile" ]]; then
      # Only in global → use global
      cp "$gfile" "$outfile"
      only_global=$((only_global + 1))
    elif diff -q "$gfile" "$pfile" >/dev/null 2>&1; then
      # Identical → use either
      cp "$pfile" "$outfile"
      identical=$((identical + 1))
    else
      # Both exist and differ — resolve by mtime
      local gmtime ptime
      gmtime=$(stat -f %m "$gfile" 2>/dev/null || stat -c %Y "$gfile" 2>/dev/null)
      ptime=$(stat -f  %m "$pfile" 2>/dev/null || stat -c %Y "$pfile" 2>/dev/null)
      local diff_secs=$(( gmtime - ptime ))
      [[ $diff_secs -lt 0 ]] && diff_secs=$(( -diff_secs ))

      if (( diff_secs > 60 )); then
        # Clear time difference — use newer file
        if (( gmtime > ptime )); then
          cp "$gfile" "$outfile"
          log "  auto: $dir/$relpath → global (newer by $diff_secs s)"
        else
          cp "$pfile" "$outfile"
          log "  auto: $dir/$relpath → project (newer by $diff_secs s)"
        fi
        auto_resolved=$((auto_resolved + 1))
      else
        # Same-age conflict — project wins as tiebreak; flag for user
        cp "$pfile" "$outfile"
        CONFLICTS+=("$dir/$relpath: both versions differ, same mtime (±${diff_secs}s) — used project copy")
        auto_resolved=$((auto_resolved + 1))
      fi
    fi
  done

  ok "$dir (global-only:$only_global  project-only:$only_project  identical:$identical  auto-resolved:$auto_resolved)"
}

echo "▶ Union-merging ~/.claude/ + .claude/ directories..."
for dir in "${CLAUDE_DIRS[@]}"; do
  union_dir "$dir"
done

# ── Rsync root-level directories ─────────────────────────────────────────────
echo "▶ Syncing root directories..."
for dir in "${ROOT_DIRS[@]}"; do
  src="$PROJECT_ROOT/$dir/"
  dst="./$dir/"
  if [[ ! -d "$src" ]]; then
    warn "$dir not found at $src — skipping"
    continue
  fi
  mkdir -p "$dst"
  rsync -a \
    --exclude='*.pyc' \
    --exclude='__pycache__/' \
    --exclude='.DS_Store' \
    --exclude='*.ttf' \
    --exclude='*.otf' \
    --exclude='*.woff' \
    --exclude='*.woff2' \
    --exclude='*.eot' \
    --exclude='*.png' \
    --exclude='*.jpg' \
    --exclude='*.jpeg' \
    --exclude='*.gif' \
    --exclude='*.ico' \
    --exclude='*.svg' \
    --exclude='*.webp' \
    --exclude='*.mp4' \
    --exclude='*.mp3' \
    --exclude='*.wav' \
    --exclude='*.pdf' \
    --exclude='*.zip' \
    --exclude='*.tar' \
    --exclude='*.gz' \
    --exclude='*.xsd' \
    --exclude='*.xml' \
    --exclude='*.testmondata' \
    --exclude='*.db' \
    --exclude='*.sqlite' \
    --exclude='*.sqlite3' \
    "$src" "$dst"
  ok "$dir"
done


# ── Remove files that must not be in the public template ─────────────────────
# settings.json / settings.local.json: MCP auth tokens + bypassPermissions flags (never publish)
rm -f ".claude/settings.json"
rm -f ".claude/settings.local.json"
# exportcommands.py: deprecated 2347-line Python script, contains hardcoded paths
# that cannot be filtered (it's in FILTER_SKIP to protect its regex patterns)
rm -f ".claude/commands/exportcommands.py"

# ── Copy GitHub workflows (examples only) ───────────────────────────────────
if [[ -d "$PROJECT_ROOT/.github/workflows" ]]; then
  mkdir -p "workflows"
  rsync -a \
    --include='*.yml' --include='*.yaml' --exclude='*' \
    "$PROJECT_ROOT/.github/workflows/" "workflows/"
  ok "workflows (examples)"
fi

# ── Apply content filters ────────────────────────────────────────────────────
echo "▶ Applying content filters..."
while IFS= read -r -d '' file; do
  apply_filters "$file"
done < <(find .claude orchestration automation ralph workflows \
  -type f \( -name '*.md' -o -name '*.py' -o -name '*.sh' -o -name '*.yml' -o -name '*.yaml' \) \
  -print0 2>/dev/null)
ok "Filters applied"

# ── Hardcoded path scan ──────────────────────────────────────────────────────
echo "▶ Scanning for leaked paths..."
LEAKED=$(grep -rl \
  --include='*.md' --include='*.py' --include='*.sh' --include='*.yml' --include='*.yaml' \
  -e '/Users/jleechan' -e 'jleechantest@gmail' \
  .claude orchestration automation ralph workflows 2>/dev/null \
  | grep -v exportcommands || true)
if [[ -n "$LEAKED" ]]; then
  warn "Hardcoded paths found — check filter list:"
  echo "$LEAKED" | sed 's/^/     /'
fi

# ── Update README via Claude CLI (preserve existing, update changelog only) ──
echo "▶ Updating README.md via Claude..."

# Capture diff stat BEFORE git add so we know what changed vs previous state
DIFF_STAT=$(git diff --stat 2>/dev/null || true)
NEW_FILES=$(git status --short 2>/dev/null | grep '^?' | awk '{print $2}' | head -20 || true)

if command -v claude >/dev/null 2>&1 && [[ -f "README.md" ]]; then
  EXISTING_README=$(cat README.md)
  COMMANDS_COUNT=$(find .claude/commands -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  SKILLS_COUNT=$(find .claude/skills -name '*.md' 2>/dev/null | wc -l | tr -d ' ')

  README_PROMPT="You are updating the README for the jleechanorg/claude-commands GitHub repository.

Here is the EXISTING README (preserve all text except what needs updating):
---
${EXISTING_README}
---

Here is what changed in this export (git diff --stat):
${DIFF_STAT:-No file changes detected}

New files added this export:
${NEW_FILES:-None}

Current counts: ${COMMANDS_COUNT} commands, ${SKILLS_COUNT} skill files.

TASK — make MINIMAL updates only:
1. Add or update a ## Changelog section near the top with today's date ($(date +%Y-%m-%d)) listing new/changed files briefly
2. If new slash commands appear in the diff that are not already mentioned in the README, add a one-line entry for each in the relevant section
3. Update any command/file counts if they changed significantly
4. Preserve ALL other text EXACTLY as-is — do not rewrite, reformat, or rephrase anything else

Output ONLY the updated markdown. No preamble, no explanation, no code fences."

  # Write prompt to temp file to avoid shell quoting issues with large README content
  PROMPT_FILE=$(mktemp /tmp/exportcommands_prompt.XXXXXX)
  printf '%s' "$README_PROMPT" > "$PROMPT_FILE"
  # Run claude from a neutral temp dir (no CLAUDE.md, no git repo) to prevent the
  # exported CLAUDE.md's mandatory git-header.sh ending from corrupting README output.
  CLAUDE_NEUTRAL_DIR=$(mktemp -d /tmp/exportcommands_neutral.XXXXXX)
  # Always generate README.md.new for preview; only overwrite README.md in non-dry-run
  (cd "$CLAUDE_NEUTRAL_DIR" && claude -p "$(cat "$PROMPT_FILE")") > README.md.new 2>/dev/null \
    || { rm -f README.md.new; warn "Claude CLI failed — keeping existing README unchanged"; }
  rm -rf "$CLAUDE_NEUTRAL_DIR"
  rm -f "$PROMPT_FILE"
  if [[ -f "README.md.new" ]]; then
    if [[ "$DRY_RUN" == "false" ]]; then
      mv README.md.new README.md
      ok "README.md updated (changelog + new commands only)"
    else
      ok "README.md.new generated for preview (dry-run — not overwriting README.md)"
    fi
  fi

elif command -v claude >/dev/null 2>&1 && [[ ! -f "README.md" ]]; then
  # No existing README — generate fresh one (first-time export)
  COMMANDS_COUNT=$(find .claude/commands -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  SKILLS_COUNT=$(find .claude/skills -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  HOOKS_COUNT=$(find .claude/hooks \( -name '*.sh' -o -name '*.py' \) 2>/dev/null | wc -l | tr -d ' ')

  README_PROMPT="Generate a concise README.md for the jleechanorg/claude-commands GitHub repository.
- 1-sentence description: reference export of a Claude Code CLI configuration
- Contains: ${COMMANDS_COUNT} slash commands, ${SKILLS_COUNT} skill files, ${HOOKS_COUNT} hooks
- Quick Start: copy .claude/ dirs or run bash ~/.claude/commands/exportcommands.sh
- Directory overview: .claude/commands/, .claude/skills/, .claude/hooks/, .claude/agents/, .claude/scripts/
- List 6-8 useful commands: /pr, /copilot, /tdd, /harness, /exportcommands, /fixpr, /orch, /converge
- Include ## Changelog section with entry for $(date +%Y-%m-%d): initial export
- Under 120 lines, GitHub-flavored markdown
- Output ONLY the markdown, no preamble"

  CLAUDE_NEUTRAL_DIR=$(mktemp -d /tmp/exportcommands_neutral.XXXXXX)
  if [[ "$DRY_RUN" == "false" ]]; then
    (cd "$CLAUDE_NEUTRAL_DIR" && claude -p "$README_PROMPT") > README.md 2>/dev/null \
      && ok "README.md created (first export)" \
      || warn "Claude CLI failed — no README generated"
  else
    (cd "$CLAUDE_NEUTRAL_DIR" && claude -p "$README_PROMPT") > README.md.new 2>/dev/null \
      && ok "README.md.new generated for preview (dry-run)" \
      || warn "Claude CLI failed — no README preview generated"
  fi
  rm -rf "$CLAUDE_NEUTRAL_DIR"
else
  warn "Skipping README update (claude CLI not found)"
fi

# ── Report unresolved conflicts ──────────────────────────────────────────────
if [[ ${#CONFLICTS[@]} -gt 0 ]]; then
  warn "Unresolved same-age conflicts (project copy used as tiebreak):"
  for c in "${CONFLICTS[@]}"; do
    warn "  $c"
  done
fi

# ── Commit & push ────────────────────────────────────────────────────────────
git add -A

if git diff --cached --quiet; then
  echo "No changes detected — nothing to export."
  exit 0
fi

CHANGED=$(git diff --cached --stat | tail -1)
git commit -m "export: $(date +%Y-%m-%d) — $CHANGED"

if [[ "$DRY_RUN" == "true" ]]; then
  echo "DRY RUN — skipping push and PR creation."
  echo "Branch: $BRANCH | Repo: $REPO_DIR"
  exit 0
fi

git push -u origin "$BRANCH"

PR_STDERR=$(mktemp /tmp/exportcommands_pr_err.XXXXXX)
PR_URL=$(gh api repos/"$TARGET_REPO"/pulls --method POST \
  -f title="Claude Commands Export $(date +%Y-%m-%d)" \
  -f head="$BRANCH" \
  -f base="main" \
  -f body="Automated export. Source files overwrite target; target-only files preserved.

Changed: $CHANGED" \
  --jq '.html_url' 2>"$PR_STDERR") || {
    warn "PR creation failed: $(cat "$PR_STDERR")"
    rm -f "$PR_STDERR"
    exit 1
  }
rm -f "$PR_STDERR"

echo ""
echo "✅ Export complete!"
echo "   PR: $PR_URL"
echo "   Branch: $BRANCH"
