#!/usr/bin/env bash
# exportcommands.sh — Export ~/.claude/ dirs to jleechanorg/claude-commands
#
# Behavior:
#   - Source files overwrite target files (rsync default)
#   - Files only in target are PRESERVED (--no-delete)
#   - README.md is regenerated by Claude CLI
#   - Content filters strip project-specific strings
#
# Usage: bash ~/.claude/commands/exportcommands.sh [--dry-run]

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────────────
TARGET_REPO="jleechanorg/claude-commands"
BRANCH="export-$(date +%Y%m%d-%H%M%S)"
REPO_DIR="$(mktemp -d)/claude-commands"
SOURCE_CLAUDE="$HOME/.claude"
# Detect project root (git root of the worldarchitect repo, not this script's location)
PROJECT_ROOT="$(git -C "$HOME/projects/worktree_review" rev-parse --show-toplevel 2>/dev/null \
  || git -C "$HOME" rev-parse --show-toplevel 2>/dev/null \
  || echo "$HOME/projects/worktree_review")"

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# Dirs from ~/.claude/ → .claude/<dir> in target repo
CLAUDE_DIRS=(commands skills hooks agents scripts)

# Dirs from project root → repo root in target repo
ROOT_DIRS=(orchestration automation ralph)

# Files to exclude from content filtering (contain literal regex patterns)
FILTER_SKIP=(exportcommands.py exportcommands.sh loc_simple.sh)

# Content filter substitutions (applied to all .md .py .sh .yml files)
declare -a SUBS=(
  's|worldarchitect\.ai|your-project.com|g'
  's|worldarchitect-ci|\${PROJECT_NAME:-your-project}-ci|g'
  's|\bjleechan\b|\$USER|g'
  's|jleechantest@gmail\.com|<your-email@gmail.com>|g'
  's|mvp_site/|\$PROJECT_ROOT/|g'
  's|WorldArchitect\.AI|Your Project|g'
  's|TESTING=true vpython|TESTING=true python|g'
  's|jleechanorg/worldarchitect\.ai|\$GITHUB_REPOSITORY|g'
)

# ── Helpers ─────────────────────────────────────────────────────────────────
log()  { echo "  $*"; }
ok()   { echo "  ✅ $*"; }
warn() { echo "  ⚠️  $*" >&2; }

# macOS vs GNU sed portability
_sed_inplace() {
  if sed --version 2>/dev/null | grep -q GNU; then
    sed -i "$@"
  else
    sed -i '' "$@"
  fi
}

apply_filters() {
  local file="$1"
  local base; base="$(basename "$file")"
  for skip in "${FILTER_SKIP[@]}"; do
    [[ "$base" == "$skip" ]] && return 0
  done
  for sub in "${SUBS[@]}"; do
    _sed_inplace "$sub" "$file"
  done
}

# ── Clone & branch ──────────────────────────────────────────────────────────
echo "▶ Cloning $TARGET_REPO..."
gh repo clone "$TARGET_REPO" "$REPO_DIR"
cd "$REPO_DIR"

git config user.email "claude-export@anthropic.com"
git config user.name "Claude Export"
git config commit.gpgsign false

git checkout main
git pull --ff-only origin main
git checkout -b "$BRANCH"

# ── Rsync .claude/ directories ──────────────────────────────────────────────
echo "▶ Syncing .claude/ directories..."
for dir in "${CLAUDE_DIRS[@]}"; do
  src="$SOURCE_CLAUDE/$dir/"
  dst=".claude/$dir/"
  if [[ ! -d "$src" ]]; then
    warn "$dir not found at $src — skipping"
    continue
  fi
  mkdir -p "$dst"
  rsync -a --no-delete \
    --exclude='*.pyc' \
    --exclude='__pycache__/' \
    --exclude='.DS_Store' \
    "$src" "$dst"
  ok "$dir"
done

# ── Rsync root-level directories ─────────────────────────────────────────────
echo "▶ Syncing root directories..."
for dir in "${ROOT_DIRS[@]}"; do
  src="$PROJECT_ROOT/$dir/"
  dst="./$dir/"
  if [[ ! -d "$src" ]]; then
    warn "$dir not found at $src — skipping"
    continue
  fi
  mkdir -p "$dst"
  rsync -a --no-delete \
    --exclude='*.pyc' \
    --exclude='__pycache__/' \
    --exclude='.DS_Store' \
    "$src" "$dst"
  ok "$dir"
done

# ── Copy settings.json ───────────────────────────────────────────────────────
if [[ -f "$SOURCE_CLAUDE/settings.json" ]]; then
  cp "$SOURCE_CLAUDE/settings.json" ".claude/settings.json"
  ok "settings.json"
fi

# ── Copy GitHub workflows (examples only) ───────────────────────────────────
if [[ -d "$PROJECT_ROOT/.github/workflows" ]]; then
  mkdir -p "workflows"
  rsync -a --no-delete \
    --include='*.yml' --include='*.yaml' --exclude='*' \
    "$PROJECT_ROOT/.github/workflows/" "workflows/"
  ok "workflows (examples)"
fi

# ── Apply content filters ────────────────────────────────────────────────────
echo "▶ Applying content filters..."
while IFS= read -r -d '' file; do
  apply_filters "$file"
done < <(find .claude orchestration automation ralph workflows \
  -type f \( -name '*.md' -o -name '*.py' -o -name '*.sh' -o -name '*.yml' -o -name '*.yaml' \) \
  -print0 2>/dev/null)
ok "Filters applied"

# ── Hardcoded path scan ──────────────────────────────────────────────────────
echo "▶ Scanning for leaked paths..."
LEAKED=$(grep -rl --include='*.md' --include='*.py' --include='*.sh' \
  -e '/Users/jleechan' -e 'jleechantest@gmail' \
  .claude orchestration automation 2>/dev/null \
  | grep -v exportcommands || true)
if [[ -n "$LEAKED" ]]; then
  warn "Hardcoded paths found — check filter list:"
  echo "$LEAKED" | sed 's/^/     /'
fi

# ── Regenerate README via Claude CLI ─────────────────────────────────────────
echo "▶ Regenerating README.md via Claude..."
COMMANDS_COUNT=$(find .claude/commands -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
SKILLS_COUNT=$(find .claude/skills -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
HOOKS_COUNT=$(find .claude/hooks -name '*.sh' -o -name '*.py' 2>/dev/null | wc -l | tr -d ' ')

README_PROMPT="Generate a concise, clear README.md for the jleechanorg/claude-commands GitHub repository.

Context:
- This repo is a reference export of a Claude Code CLI configuration
- It contains: $COMMANDS_COUNT slash commands, $SKILLS_COUNT skill files, $HOOKS_COUNT hooks
- Directories: .claude/commands/, .claude/skills/, .claude/hooks/, .claude/agents/, .claude/scripts/
- These are generic templates — users adapt them to their own projects

Requirements:
- Start with a 1-sentence description of what the repo is
- Include a Quick Start section showing how to install (localexportcommands.sh or manual copy)
- Include a brief directory structure overview
- List 5-8 of the most useful slash commands (e.g. /pr, /copilot, /tdd, /harness, /exportcommands, /fixpr, /orch)
- Keep it under 120 lines total
- Use GitHub-flavored markdown
- Do NOT include any WorldArchitect.AI or jleechan-specific content
- Output ONLY the markdown, no preamble or explanation"

if command -v claude >/dev/null 2>&1 && [[ "$DRY_RUN" == "false" ]]; then
  claude -p "$README_PROMPT" > README.md 2>/dev/null && ok "README.md regenerated" \
    || { warn "Claude CLI failed — keeping existing README"; }
else
  warn "Skipping README regeneration (dry-run or claude CLI not found)"
fi

# ── Commit & push ────────────────────────────────────────────────────────────
git add -A

if git diff --cached --quiet; then
  echo "No changes detected — nothing to export."
  exit 0
fi

CHANGED=$(git diff --cached --stat | tail -1)
git commit -m "export: $(date +%Y-%m-%d) — $CHANGED"

if [[ "$DRY_RUN" == "true" ]]; then
  echo "DRY RUN — skipping push and PR creation."
  echo "Branch: $BRANCH | Repo: $REPO_DIR"
  exit 0
fi

git push -u origin "$BRANCH"

PR_URL=$(gh pr create \
  --title "Claude Commands Export $(date +%Y-%m-%d)" \
  --base main \
  --body "Automated export. Source files overwrite target; target-only files preserved (--no-delete).

Changed: $CHANGED" \
  --json url --jq '.url')

echo ""
echo "✅ Export complete!"
echo "   PR: $PR_URL"
echo "   Branch: $BRANCH"
