# Generated by Django 4.2.7 on 2025-09-26 12:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable tenant name', max_length=100, unique=True)),
                ('schema_name', models.CharField(help_text='Database schema name for this tenant', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Schema name must start with a letter and contain only lowercase letters, numbers, and underscores', regex='^[a-z][a-z0-9_]*$')])),
                ('domain', models.CharField(blank=True, help_text='Primary domain for this tenant', max_length=253, null=True, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Subdomain identifier', max_length=63, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active and accessible')),
                ('max_users', models.PositiveIntegerField(default=100, help_text='Maximum number of users allowed for this tenant')),
                ('storage_limit_gb', models.PositiveIntegerField(default=10, help_text='Storage limit in gigabytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Primary owner/administrator of this tenant', on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_graphql', models.BooleanField(default=True)),
                ('enable_api_access', models.BooleanField(default=True)),
                ('enable_file_uploads', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('theme_color', models.CharField(default='#007bff', help_text='Primary theme color (hex)', max_length=7)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('custom_css', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('api_rate_limit', models.PositiveIntegerField(default=1000, help_text='API requests per hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='tenants.tenant')),
            ],
            options={
                'db_table': 'public_tenant_configuration',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tenant_memberships', through='tenants.TenantMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'is_active'], name='tenants_ten_tenant__b981b3_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='tenants_ten_user_id_8b073c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('tenant', 'user')},
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['schema_name'], name='public_tena_schema__fe364c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['domain'], name='public_tena_domain_00067a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='public_tena_is_acti_f68cc2_idx'),
        ),
    ]
