#!/usr/bin/env python3
"""Wrapper script for /commentfetch command"""
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '_copilot_modules'))
from commentfetch import main

if __name__ == '__main__':
    sys.exit(main())