# âš ï¸ EXAMPLE WORKFLOW - REQUIRES INTEGRATION
# This workflow was exported from a working project and serves as an EXAMPLE ONLY.
# You MUST adapt the following before using:
# - $GCP_PROJECT_ID â†’ Your Google Cloud project ID
# - $GITHUB_REPOSITORY â†’ Your repository (owner/repo)
# - $GITHUB_OWNER â†’ Your GitHub username or org
# - Service account configurations and secrets
# - Environment-specific variables and paths
#
# See workflows/README.md for integration instructions.
# ---

name: Claude Bot Processor
on:
  repository_dispatch:
    types: [claude-command]

jobs:
  claude:
    runs-on: ${{ fromJson(vars.SELF_HOSTED_RUNNER_LABELS || '["self-hosted", "claude", "ubuntu"]') }}
    timeout-minutes: 10  # Prevent hung processes
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1  # v4.1.1

      - name: Runner control plane
        uses: ./.github/actions/runner-control-plane


      - name: Extract
        id: x
        run: |
          echo "Debug: GitHub event file content:"
          cat "$GITHUB_EVENT_PATH"
          echo ""
          P=$(jq -r '.client_payload.slash_command.args.all // empty' "$GITHUB_EVENT_PATH")
          CID=$(jq -r '.client_payload.github.payload.comment.id // empty' "$GITHUB_EVENT_PATH")
          echo "Debug: Extracted prompt='$P'"
          echo "Debug: Comment ID='$CID'"
          echo "prompt=$P"  >> $GITHUB_OUTPUT
          echo "cid=$CID"  >> $GITHUB_OUTPUT

      - name: Call Claude
        id: y
        run: |
          RUNNER_SCRIPT="$GITHUB_WORKSPACE/self-hosted-runner/run-in-ci-container.sh"
          chmod +x "$RUNNER_SCRIPT"
          # Capture only stdout (curl response); wrapper diagnostics go to stderr (Actions log)
          "$RUNNER_SCRIPT" \
            --workspace "$GITHUB_WORKSPACE" \
            --cmd "curl -s --data-urlencode 'prompt=${{ steps.x.outputs.prompt }}' '${{ secrets.CLAUDE_ENDPOINT }}'" \
            > /tmp/claude-response.txt
          echo "answer=$(cat /tmp/claude-response.txt | head -c 65000)" >> $GITHUB_OUTPUT

      - name: Comment back
        uses: peter-evans/create-or-update-comment@9a932638a9f5079d84f4e9f56f0f2a5ceee4b2d1  # v4.0.0
        with:
          comment-id: ${{ steps.x.outputs.cid }}
          body: |
            **ðŸ¤– Claude Bot Reply**
            ```
            ${{ steps.y.outputs.answer }}
            ```
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
