# ⚠️ EXAMPLE WORKFLOW - REQUIRES INTEGRATION
# This workflow was exported from a working project and serves as an EXAMPLE ONLY.
# You MUST adapt the following before using:
# - $GCP_PROJECT_ID → Your Google Cloud project ID
# - $GITHUB_REPOSITORY → Your repository (owner/repo)
# - $GITHUB_OWNER → Your GitHub username or org
# - Service account configurations and secrets
# - Environment-specific variables and paths
#
# See workflows/README.md for integration instructions.
# ---

name: Coverage Report

# Cancel in-progress runs when new commits are pushed to same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Run on main pushes only to update coverage baseline and badge.
# Coverage was previously also triggered on pull_request, but this duplicated
# the full test suite execution already performed by test.yml (~14 min wasted
# per PR push). test.yml is the primary test gatekeeper; this workflow only
# needs to maintain the coverage baseline on main.
on:
  push:
    branches: [main]
    paths:
      - 'mvp_site/**/*.py'
      - 'coverage.sh'
      - '.github/workflows/coverage.yml'

permissions:
  contents: write

jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: [self-hosted, claude]
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          persist-credentials: true

      - name: Runner control plane
        id: control-plane
        run: |
          echo "preflight_exit_code=0" >> "$GITHUB_OUTPUT"
          echo "infra_failure_class=" >> "$GITHUB_OUTPUT"
          echo "preflight_json=${RUNNER_TEMP:-/tmp}/runner_health.json" >> "$GITHUB_OUTPUT"
          echo "quarantined=false" >> "$GITHUB_OUTPUT"
          echo "score=0" >> "$GITHUB_OUTPUT"
          echo "::notice::Runner control plane skipped - add .github/actions/runner-control-plane for full preflight"

      - name: Set up Python 3.11
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809  # v4.2.4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-coverage-python-3.11-${{ hashFiles('mvp_site/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-coverage-python-3.11-

      - name: Install dependencies
        run: |
          rm -rf venv
          python3 -m venv venv
          VENV_PY="$PWD/venv/bin/python"
          VENV_PIP="$PWD/venv/bin/pip"
          "$VENV_PIP" install --upgrade pip setuptools wheel
          "$VENV_PIP" install -r mvp_site/requirements.txt
          "$VENV_PIP" install coverage pytest
          echo "$PWD/venv/bin" >> "$GITHUB_PATH"
          echo "VIRTUAL_ENV=$PWD/venv" >> "$GITHUB_ENV"

      - name: Run tests with coverage
        run: |
          VENV_PY="$PWD/venv/bin/python"

          # Set environment and PYTHONPATH (run from project root)
          export TESTING=true
          export TESTING_AUTH_BYPASS=true
          export PYTHONPATH="${PWD}:$PYTHONPATH"

          # Playwright usage is not needed for unit tests, but if needed later:
          # pip install playwright && playwright install chromium

          # Create .coveragerc for py-cov-action compatibility
          cat > .coveragerc << 'EOF'
          [run]
          relative_files = true
          source = mvp_site
          omit =
              */tests/*
              */testing_framework/*
              */venv/*
              */__pycache__/*

          [report]
          exclude_lines =
              pragma: no cover
              def __repr__
              raise NotImplementedError
          EOF
          
          # Run tests SEQUENTIALLY using the shell script to avoid OOM (Exit code 137)
          # The single 'coverage run' command causes memory to accumulate over 240+ test files.
          # We use set +e to capture failures but continue to report generation.
          # We also verify dependencies before running.
          chmod +x run_tests_with_coverage.sh
          
          set +e
          # Script now auto-detects mvp_site at root and runs from root (generating .coverage at root)
          ./run_tests_with_coverage.sh --no-html
          test_exit_code=$?
          set -e
          
          if [ "${test_exit_code}" -ne 0 ]; then
            echo "::error::Tests failed (exit code ${test_exit_code}). Generating reports before failing."
          fi
          
          if [ ! -f .coverage ]; then
             echo "::warning::No .coverage file found at root"
          fi

          # Generate reports using the root .coveragerc
          # Suppress errors here too just in case coverage data is partial
          "$VENV_PY" -m coverage report --format=markdown > coverage_report.md || echo "Coverage report generation failed"
          "$VENV_PY" -m coverage xml -o coverage.xml || echo "Coverage XML generation failed"
          "$VENV_PY" -m coverage json -o coverage.json || echo "Coverage JSON generation failed"
          
          # Exit with original test failure code if tests failed
          if [ "${test_exit_code}" -ne 0 ]; then
            exit "${test_exit_code}"
          fi

      - name: Update coverage baseline (main)
        if: (success() || failure()) && github.ref == 'refs/heads/main'
        uses: py-cov-action/python-coverage-comment-action@fb02115d6115e7b3325dc3295fe1dcfb1919248a  # v3.32
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 80
          MINIMUM_ORANGE: 60

      - name: Generate coverage badge
        if: (success() || failure()) && github.ref == 'refs/heads/main'
        run: |
          VENV_PY="$PWD/venv/bin/python"

          # Extract total coverage percentage
          COVERAGE=$("$VENV_PY" -m coverage report 2>/dev/null | tail -1 | awk '{print $4}' | tr -d '%')

          # Validate coverage is numeric
          if ! [[ "$COVERAGE" =~ ^[0-9]+$ ]]; then
            COVERAGE=$("$VENV_PY" -m coverage report 2>/dev/null | grep "^TOTAL" | awk '{print $NF}' | tr -d '%')
            if ! [[ "$COVERAGE" =~ ^[0-9]+$ ]]; then
              echo "::warning::Could not parse coverage for badge generation, defaulting to 0"
              COVERAGE=0
            fi
          fi

          echo "Total coverage: ${COVERAGE}%"

          # Determine badge color
          if [ "$COVERAGE" -ge 80 ]; then
            COLOR="brightgreen"
          elif [ "$COVERAGE" -ge 60 ]; then
            COLOR="green"
          elif [ "$COVERAGE" -ge 40 ]; then
            COLOR="yellow"
          else
            COLOR="red"
          fi

          # Save coverage data for badge
          echo "COVERAGE=${COVERAGE}" >> $GITHUB_ENV
          echo "BADGE_COLOR=${COLOR}" >> $GITHUB_ENV

      - name: Update runner health score
        id: runner-health-update
        if: always()
        run: |
          chmod +x scripts/runner_health_score.py
          DELTA=-1
          REASON="coverage:success"

          if [ -n "${{ steps.control-plane.outputs.preflight_exit_code }}" ] && [ "${{ steps.control-plane.outputs.preflight_exit_code }}" != "0" ]; then
            DELTA=4
            REASON="preflight:${{ steps.control-plane.outputs.infra_failure_class }}"
          elif [ "${{ steps.control-plane.outputs.quarantined }}" = "true" ]; then
            DELTA=0
            REASON="quarantine:skipped"
          elif [ "${{ job.status }}" = "cancelled" ]; then
            DELTA=0
            REASON="coverage:cancelled"
          elif [ "${{ job.status }}" != "success" ]; then
            DELTA=1
            REASON="coverage:failed"
          fi

          scripts/runner_health_score.py \
            --runner "${RUNNER_NAME:-unknown}" \
            --threshold 6 \
            --github-output "$GITHUB_OUTPUT" \
            update \
            --delta "$DELTA" \
            --reason "$REASON"

      - name: Collect runner health artifacts
        if: always()
        run: |
          mkdir -p "${RUNNER_TEMP}/runner-health"
          cp "${{ steps.control-plane.outputs.preflight_json }}" "${RUNNER_TEMP}/runner-health/runner_health.json" 2>/dev/null || true
          cp "${HOME}/.cache/${PROJECT_NAME:-${GITHUB_REPOSITORY##*/}}-ci/runner-health-score.json" "${RUNNER_TEMP}/runner-health/runner_health_score.json" 2>/dev/null || true

      - name: Upload coverage reports
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3  # v4.3.1
        if: always()
        with:
          name: coverage-reports
          path: |
            coverage_report.md
            coverage.xml
            coverage.json
            .coverage
            ${{ runner.temp }}/runner-health/runner_health.json
            ${{ runner.temp }}/runner-health/runner_health_score.json
          if-no-files-found: warn
          retention-days: 30

      - name: Post coverage summary
        if: always()
        run: |
          VENV_PY="$PWD/venv/bin/python"

          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f coverage_report.md ]; then
            cat coverage_report.md >> $GITHUB_STEP_SUMMARY
          else
            "$VENV_PY" -m coverage report --format=markdown >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "Coverage report generation failed" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "## Runner Health" >> "$GITHUB_STEP_SUMMARY"
          echo "- Quarantine score before run: ${{ steps.control-plane.outputs.score }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Quarantined before run: ${{ steps.control-plane.outputs.quarantined }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Preflight exit: ${{ steps.control-plane.outputs.preflight_exit_code }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Score after run: ${{ steps.runner-health-update.outputs.score }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Quarantined now: ${{ steps.runner-health-update.outputs.quarantined }}" >> "$GITHUB_STEP_SUMMARY"
