# ⚠️ EXAMPLE WORKFLOW - REQUIRES INTEGRATION
# This workflow was exported from a working project and serves as an EXAMPLE ONLY.
# You MUST adapt the following before using:
# - $GCP_PROJECT_ID → Your Google Cloud project ID
# - $GITHUB_REPOSITORY → Your repository (owner/repo)
# - $GITHUB_OWNER → Your GitHub username or org
# - Service account configurations and secrets
# - Environment-specific variables and paths
#
# See workflows/README.md for integration instructions.
# ---

name: Hook Tests

# Optimized CI triggers - no duplication on PR branches
on:
  pull_request:              # Run on all PRs regardless of target branch
    paths:
      - '.claude/hooks/**'
      - '.github/workflows/hook-tests.yml'
  push:
    branches: [ main, dev ]  # Run on pushes to main/dev for post-merge validation
    paths:
      - '.claude/hooks/**'
      - '.github/workflows/hook-tests.yml'

jobs:
  limit-pr-runs:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1 # v4.1.1
      - name: Limit PR runs
        uses: ./.github/actions/limit-pr-runs
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
  try-self-hosted:
    runs-on: [self-hosted, claude]
    timeout-minutes: 10
    continue-on-error: true
    outputs:
      success: ${{ steps.mark-success.outputs.success }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1  # v4.1.1
    
    - name: Set up Python 3.11
      if: runner.os == 'Linux'
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
      with:
        python-version: '3.11'

    - name: Install jq (for hook tests)
      if: runner.os == 'Linux'
      run: |
        # Note: macOS includes jq pre-installed at /usr/bin/jq (Apple ships jq 1.7.1+)
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Run hook tests
      run: |
        cd .claude/hooks/tests
        echo "🧪 Running Claude Code Hook Tests..."
        echo "========================================"
        
        # Make all test scripts executable
        chmod +x *.sh
        chmod +x ../*.sh
        
        # Run the main test suite
        if bash run_all_hook_tests.sh; then
          echo ""
          echo "✅ All hook tests passed!"
          exit 0
        else
          echo ""
          echo "❌ Some hook tests failed!"
          exit 1
        fi
    
    - name: Upload test results
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3  # v4.3.1
      if: always()
      with:
        name: hook-test-results
        path: |
          .claude/hooks/tests/*.log
          /tmp/compose-commands-*.log
        retention-days: 7
        if-no-files-found: ignore

    - name: Mark successful completion
      id: mark-success
      if: success()
      run: echo "success=true" >> $GITHUB_OUTPUT

  fallback-github-hosted:
    needs: try-self-hosted
    if: needs.try-self-hosted.outputs.success != 'true'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1  # v4.1.1

    - name: Set up Python 3.11
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
      with:
        python-version: '3.11'

    - name: Install jq (for hook tests)
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Run hook tests
      run: |
        cd .claude/hooks/tests
        echo "🧪 Running Claude Code Hook Tests (GitHub-hosted fallback)..."
        echo "========================================"

        # Make all test scripts executable
        chmod +x *.sh
        chmod +x ../*.sh

        # Run the main test suite
        if bash run_all_hook_tests.sh; then
          echo ""
          echo "✅ All hook tests passed!"
          exit 0
        else
          echo ""
          echo "❌ Some hook tests failed!"
          exit 1
        fi

    - name: Upload test results
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3  # v4.3.1
      if: always()
      with:
        name: hook-test-results-fallback
        path: |
          .claude/hooks/tests/*.log
          /tmp/compose-commands-*.log
        retention-days: 7
        if-no-files-found: ignore
