# ⚠️ EXAMPLE WORKFLOW - REQUIRES INTEGRATION
# This workflow was exported from a working project and serves as an EXAMPLE ONLY.
# You MUST adapt the following before using:
# - $GCP_PROJECT_ID → Your Google Cloud project ID
# - $GITHUB_REPOSITORY → Your repository (owner/repo)
# - $GITHUB_OWNER → Your GitHub username or org
# - Service account configurations and secrets
# - Environment-specific variables and paths
#
# See workflows/README.md for integration instructions.
# ---

name: MCP Smoke Tests [Mock APIs]

# Security permissions
permissions:
  contents: read
  pull-requests: read

# Run on all PRs and pushes to main/dev
on:
  pull_request:
    paths:
      - 'mvp_site/mcp_*.py'
      - 'mvp_site/tests/mcp_*.py'
      - 'mvp_site/tests/test_mcp_*.py'
      - '.github/workflows/mcp-smoke-tests.yml'
      - 'scripts/mcp_smoke_test.sh'
  push:
    branches: [ main, dev ]
    paths:
      - 'mvp_site/mcp_*.py'
      - 'mvp_site/tests/mcp_*.py'
      - 'mvp_site/tests/test_mcp_*.py'
      - '.github/workflows/mcp-smoke-tests.yml'
      - 'scripts/mcp_smoke_test.sh'

jobs:
  smoke-tests:
    name: MCP Server Smoke Tests [Mock APIs]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PYTHON_VERSION: '3.11'
      TESTING: true
      FLASK_ENV: testing
      TEST_MODE: mock
      MOCK_SERVICES_MODE: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1  # v4.1.1
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip dependencies
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809  # v4.2.4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('mvp_site/requirements*.txt', 'requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mvp_site/requirements.txt
        if [ -f mvp_site/requirements-test.txt ]; then pip install -r mvp_site/requirements-test.txt; fi

    - name: Setup test environment
      run: |
        # Create necessary directories
        mkdir -p tmp/your-project.com/test

    - name: Run MCP smoke tests
      run: |
        chmod +x scripts/mcp_smoke_test.sh
        ./scripts/mcp_smoke_test.sh

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3  # v4.3.1
      with:
        name: mcp-smoke-test-results-mock-apis
        path: |
          tmp/your-project.com/test/*.log
          tmp/your-project.com/test/smoke-test-results.json
          tmp/your-project.com/test/mcp-requests-responses.json
        retention-days: 7
