# ⚠️ EXAMPLE WORKFLOW - REQUIRES INTEGRATION
# This workflow was exported from a working project and serves as an EXAMPLE ONLY.
# You MUST adapt the following before using:
# - $GCP_PROJECT_ID → Your Google Cloud project ID
# - $GITHUB_REPOSITORY → Your repository (owner/repo)
# - $GITHUB_OWNER → Your GitHub username or org
# - Service account configurations and secrets
# - Environment-specific variables and paths
#
# See workflows/README.md for integration instructions.
# ---

name: Deploy PR Preview (Rotating Pool)

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'mvp_site/**'
      - 'infrastructure/**'
      - 'deploy.sh'
      - 'scripts/deploy_common.sh'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'scripts/**'
      - '.github/workflows/pr-preview.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-preview:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      GCP_REGION: us-central1
      GCP_PROJECT: $GCP_PROJECT_ID
      CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c  # v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200  # v2
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Ensure required Google Cloud APIs are enabled
        run: |
          set -euo pipefail
          gcloud services enable \
            run.googleapis.com \
            cloudbuild.googleapis.com \
            artifactregistry.googleapis.com \
            --project="${{ env.GCP_PROJECT }}" \
            --quiet

      - name: Assign server from pool
        id: server_pool
        env:
          PR_NUMBER: ${{ github.event.number }}
          GCP_PROJECT: ${{ env.GCP_PROJECT }}
          GCP_REGION: ${{ env.GCP_REGION }}
        run: |
          set -euo pipefail
          echo "🎯 Assigning server for PR #${PR_NUMBER}"

          # Make script executable
          chmod +x .github/scripts/pr-server-pool.sh

          # Run pool assignment script (queries Cloud Run)
          ASSIGNMENT=$(.github/scripts/pr-server-pool.sh assign "$PR_NUMBER")

          # Parse JSON output
          SERVER=$(echo "$ASSIGNMENT" | jq -r '.server')
          SERVICE_NAME=$(echo "$ASSIGNMENT" | jq -r '.serviceName')
          EVICTED=$(echo "$ASSIGNMENT" | jq -r '.evicted')

          echo "server=$SERVER" >> "$GITHUB_OUTPUT"
          echo "service_name=$SERVICE_NAME" >> "$GITHUB_OUTPUT"
          echo "evicted=$EVICTED" >> "$GITHUB_OUTPUT"

          echo "✅ Assigned: $SERVICE_NAME (server: $SERVER)"

          if [ "$EVICTED" != "null" ]; then
            echo "⚠️  Evicted PR #${EVICTED} to make room"
            echo "eviction_message=⚠️ **Pool Full**: Evicted PR #${EVICTED} to assign server ${SERVER}" >> "$GITHUB_OUTPUT"
          else
            echo "eviction_message=null" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and Deploy PR Preview
        env:
          SERVICE_NAME: ${{ steps.server_pool.outputs.service_name }}
          SERVER: ${{ steps.server_pool.outputs.server }}
          GITHUB_SHA: ${{ github.sha }}
          PR_NUMBER: ${{ github.event.number }}
        timeout-minutes: 20
        run: |
          set -euo pipefail

          echo "🚀 Deploying PR #$PR_NUMBER to server $SERVER..."
          echo "Service name: $SERVICE_NAME"

          # Build and push Docker image with unique tag
          IMAGE_TAG="gcr.io/${{ env.GCP_PROJECT }}/$SERVICE_NAME:$GITHUB_SHA"

          echo "Building Docker image: $IMAGE_TAG"
          # Create inline cloudbuild.yaml to build from project root with Dockerfile in mvp_site/
          cat > /tmp/cloudbuild.yaml <<EOF
          steps:
          - name: 'gcr.io/cloud-builders/docker'
            args: ['build', '-t', '$IMAGE_TAG', '-f', 'mvp_site/Dockerfile', '.']
          images: ['$IMAGE_TAG']
          EOF

          gcloud builds submit \
            --config=/tmp/cloudbuild.yaml \
            --project="${{ env.GCP_PROJECT }}" \
            --timeout=15m \
            --quiet \
            --suppress-logs \
            . || {
            echo "⚠️ Build command returned non-zero exit code, but build may still be running"
            echo "Checking if image was created..."
            sleep 30
          }

          # Deploy to Cloud Run with PR label
          echo "Deploying to Cloud Run service: $SERVICE_NAME"
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE_TAG" \
            --region="${{ env.GCP_REGION }}" \
            --project="${{ env.GCP_PROJECT }}" \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars="FLASK_ENV=production,ENVIRONMENT=preview" \
            --set-secrets="GEMINI_API_KEY=gemini-api-key:latest,CEREBRAS_API_KEY=cerebras-api-key:latest,OPENROUTER_API_KEY=openrouter-api-key:latest" \
            --memory=512Mi \
            --cpu=1 \
            --max-instances=2 \
            --timeout=300 \
            --update-labels="pr-number=$PR_NUMBER" \
            --quiet

          echo "✅ Deployment complete!"

      - name: Verify service labels
        env:
          GCP_PROJECT: ${{ env.GCP_PROJECT }}
          GCP_REGION: ${{ env.GCP_REGION }}
          SERVICE_NAME: ${{ steps.server_pool.outputs.service_name }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "🏷️  Verifying service labels"

          ACTUAL_PR=$(gcloud run services describe "$SERVICE_NAME" \
            --project="$GCP_PROJECT" \
            --region="$GCP_REGION" \
            --format='value(metadata.labels.pr-number)' \
            --quiet || echo "none")

          if [ "$ACTUAL_PR" = "$PR_NUMBER" ]; then
            echo "✅ Service correctly labeled: pr-number=$PR_NUMBER"
          else
            echo "⚠️  Warning: Label mismatch. Expected: $PR_NUMBER, Got: $ACTUAL_PR"
            echo "   (This is non-critical - deployment succeeded)"
          fi

      - name: Fetch deployed service URL
        if: success()
        id: deployment_info
        env:
          GCP_REGION: ${{ env.GCP_REGION }}
          GCP_PROJECT: ${{ env.GCP_PROJECT }}
          SERVICE_NAME: ${{ steps.server_pool.outputs.service_name }}
        run: |
          set -euo pipefail

          SERVICE_URL=$(gcloud run services describe "$SERVICE_NAME" \
            --platform managed \
            --region "$GCP_REGION" \
            --project "$GCP_PROJECT" \
            --format 'value(status.url)' \
            --quiet)

          if [ -z "$SERVICE_URL" ]; then
            echo "Service URL not found" >&2
            exit 1
          fi

          HEALTH_URL="${SERVICE_URL%/}/health"
          MCP_URL="${SERVICE_URL%/}/mcp"

          echo "service_url=$SERVICE_URL" >> "$GITHUB_OUTPUT"
          echo "health_url=$HEALTH_URL" >> "$GITHUB_OUTPUT"
          echo "mcp_url=$MCP_URL" >> "$GITHUB_OUTPUT"

      - name: Verify preview health
        id: health_check
        if: ${{ success() && steps.deployment_info.outputs.health_url != '' }}
        env:
          HEALTH_URL: ${{ steps.deployment_info.outputs.health_url }}
          PREVIEW_URL: ${{ steps.deployment_info.outputs.service_url }}
        run: |
          set -euo pipefail
          echo "🏥 Checking preview health at: ${HEALTH_URL}"

          for attempt in $(seq 1 10); do
            if curl --fail --silent --show-error --max-time 10 "$HEALTH_URL" > /dev/null 2>&1; then
              echo "✅ Health endpoint responded on attempt ${attempt}"
              echo "health_check_passed=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi

            if curl --fail --silent --show-error --max-time 10 "$PREVIEW_URL" > /dev/null 2>&1; then
              echo "✅ Root endpoint responded on attempt ${attempt}"
              echo "health_check_passed=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi

            echo "⏳ Health check attempt ${attempt} failed, retrying in 6s..."
            sleep 6
          done

          echo "❌ Health check failed after 10 attempts" >&2
          echo "health_check_passed=false" >> "$GITHUB_OUTPUT"
          exit 1

      - name: Show pool status
        if: always()
        run: |
          set -euo pipefail
          chmod +x .github/scripts/pr-server-pool.sh
          .github/scripts/pr-server-pool.sh status

      - name: Post preview deployment comment
        if: ${{ success() && github.event_name == 'pull_request' && steps.deployment_info.outputs.service_url != '' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # v7
        env:
          PREVIEW_URL: ${{ steps.deployment_info.outputs.service_url }}
          HEALTH_URL: ${{ steps.deployment_info.outputs.health_url }}
          MCP_URL: ${{ steps.deployment_info.outputs.mcp_url }}
          SERVICE_NAME: ${{ steps.server_pool.outputs.service_name }}
          ASSIGNED_SERVER: ${{ steps.server_pool.outputs.server }}
          EVICTION_MESSAGE: ${{ steps.server_pool.outputs.eviction_message }}
          GCP_REGION: ${{ env.GCP_REGION }}
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
          WORKFLOW_NAME: ${{ github.workflow }}
          RUN_ID: ${{ github.run_id }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          JOB_STATUS: ${{ job.status }}
          HEALTH_CHECK_PASSED: ${{ steps.health_check.outputs.health_check_passed == 'true' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Validate required context
              if (!context.payload || !context.payload.pull_request) {
                core.setFailed('Missing pull_request context. Cannot post comment.');
                return;
              }

              const prNumber = context.payload.pull_request.number;
              if (!prNumber) {
                core.setFailed('Missing PR number. Cannot post comment.');
                return;
              }

              const { owner, repo } = context.repo;
              if (!owner || !repo) {
                core.setFailed('Missing repo context. Cannot post comment.');
                return;
              }

              // Validate required environment variables
              if (!process.env.PREVIEW_URL) {
                core.setFailed('Missing PREVIEW_URL. Cannot post comment.');
                return;
              }

              const marker = '<!-- pr-preview-comment:mvp-site -->';
              const workflowUrl = `${process.env.GITHUB_SERVER_URL}/${owner}/${repo}/actions/runs/${process.env.RUN_ID}`;
              const shortSha = process.env.COMMIT_SHA ? process.env.COMMIT_SHA.slice(0, 7) : 'unknown';
              const commitUrl = process.env.COMMIT_SHA 
                ? `${process.env.GITHUB_SERVER_URL}/${owner}/${repo}/commit/${process.env.COMMIT_SHA}`
                : workflowUrl;
              const evictionMessage = process.env.EVICTION_MESSAGE;
              const evictionLines =
                evictionMessage && evictionMessage !== 'null'
                  ? ['', evictionMessage, '']
                  : [];

              const deploymentSuccess = process.env.JOB_STATUS === 'success';
              const healthCheckPassed = process.env.HEALTH_CHECK_PASSED === 'true';
              // If HEALTH_CHECK_PASSED is not set, the health check step didn't run (skipped)
              const healthCheckStatus = process.env.HEALTH_URL 
                ? (process.env.HEALTH_CHECK_PASSED === undefined || process.env.HEALTH_CHECK_PASSED === ''
                  ? '⚠️ Health check skipped'
                  : (healthCheckPassed ? '✅ Health check verified' : '❌ Health check failed'))
                : '⚠️ Health check skipped';

              const commentLines = [
                marker,
                '',
                deploymentSuccess ? '## ✅ Deployment Complete!' : '## ⚠️ Deployment Completed with Warnings',
                '',
                deploymentSuccess 
                  ? '**🎉 Your PR preview is ready!**'
                  : '**⚠️ Deployment completed, but some checks may have failed.**',
                '',
                '### 🔗 Quick Access:',
                '| Service | URL |',
                '|---------|-----|',
                `| 🌐 **Preview App** | [${process.env.PREVIEW_URL}](${process.env.PREVIEW_URL}) |`,
                process.env.HEALTH_URL 
                  ? `| 🩺 **Health Check** | [${process.env.HEALTH_URL}](${process.env.HEALTH_URL}) |`
                  : '| 🩺 **Health Check** | Not available |',
                process.env.MCP_URL 
                  ? `| 📡 **MCP Endpoint** | [${process.env.MCP_URL}](${process.env.MCP_URL}) |`
                  : '| 📡 **MCP Endpoint** | Not available |',
                '',
                '> ℹ️ Use `/smoke` command to run MCP smoke tests against this preview.',
                '',
                '### 🔄 Completed Build Steps:',
                '- ✅ Server pool assignment',
                '- ✅ Docker image build',
                '- ✅ Cloud Run deployment',
                `- ${healthCheckStatus}`,
                '',
                '### 📋 Deployment Details:',
                `- **Commit:** [\`${shortSha}\`](${commitUrl})`,
                `- **Service:** \`${process.env.SERVICE_NAME || 'unknown'}\``,
                `- **Server:** \`${process.env.ASSIGNED_SERVER || 'unknown'}\``,
                `- **Region:** \`${process.env.GCP_REGION || 'unknown'}\``,
                `- **Branch:** \`${process.env.BRANCH_NAME || 'unknown'}\``,
                `- **Workflow:** [View Details](${workflowUrl})`,
                ...evictionLines,
                '',
                '🤖 *Auto-deployed via rotating server pool*',
              ].filter(line => line !== null);
              const commentBody = commentLines.join('\n');

              // Always post a NEW comment for each deployment
              const result = await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: commentBody,
              });

              core.info(`✅ Successfully posted preview comment to PR #${prNumber} (comment ID: ${result.data.id})`);
            } catch (error) {
              core.error(`❌ Failed to post preview comment: ${error.message}`);
              core.error(`Error details: ${JSON.stringify(error, null, 2)}`);
              // Don't fail the workflow if comment posting fails
              core.warning('Comment posting failed, but deployment may have succeeded');
            }

      - name: Post deployment failure comment
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # v7
        env:
          SERVICE_NAME: ${{ steps.server_pool.outputs.service_name }}
          ASSIGNED_SERVER: ${{ steps.server_pool.outputs.server }}
          GCP_REGION: ${{ env.GCP_REGION }}
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
          RUN_ID: ${{ github.run_id }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;

            const workflowUrl = `${process.env.GITHUB_SERVER_URL}/${owner}/${repo}/actions/runs/${process.env.RUN_ID}`;
            const shortSha = process.env.COMMIT_SHA.slice(0, 7);
            const commitUrl = `${process.env.GITHUB_SERVER_URL}/${owner}/${repo}/commit/${process.env.COMMIT_SHA}`;

            const commentBody = [
              '## ❌ Deployment Failed',
              '',
              'The deployment process encountered an error and could not complete.',
              '',
              '### 📋 Details:',
              `- **Commit:** [\`${shortSha}\`](${commitUrl})`,
              `- **Service:** \`${process.env.SERVICE_NAME}\``,
              `- **Server:** \`${process.env.ASSIGNED_SERVER}\``,
              `- **Region:** \`${process.env.GCP_REGION}\``,
              `- **Branch:** \`${process.env.BRANCH_NAME}\``,
              `- **Workflow:** [View Logs](${workflowUrl})`,
              '',
              '### 🔍 Next Steps:',
              `1. Check the [workflow logs](${workflowUrl}) for details`,
              '2. Review any error messages in the deployment step',
              '3. Push a new commit to retry the deployment',
              '',
              '🤖 *Auto-deployment failed via rotating server pool*',
            ].join('\n');

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: commentBody,
            });
