# ⚠️ EXAMPLE WORKFLOW - REQUIRES INTEGRATION
# This workflow was exported from a working project and serves as an EXAMPLE ONLY.
# You MUST adapt the following before using:
# - $GCP_PROJECT_ID → Your Google Cloud project ID
# - $GITHUB_REPOSITORY → Your repository (owner/repo)
# - $GITHUB_OWNER → Your GitHub username or org
# - Service account configurations and secrets
# - Environment-specific variables and paths
#
# See workflows/README.md for integration instructions.
# ---

name: Presubmit Checks

# Cancel in-progress runs when new commits are pushed to same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Security permissions
permissions:
  contents: read
  pull-requests: read
  actions: read  # Required for cache actions

# Optimized CI triggers - no duplication on PR branches
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'roadmap/**'
      - '.github/ISSUE_TEMPLATE/**'
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'roadmap/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  limit-pr-runs:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1 # v4.1.1
      - name: Limit PR runs
        uses: ./.github/actions/limit-pr-runs
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
  schema-coverage:
    name: Schema Coverage Guard
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Enforce game_state schema coverage
        run: |
          PYTHON=$(command -v python3.11 || command -v python3 || command -v python || true)
          if [ -z "$PYTHON" ]; then
            echo "::error::No suitable Python interpreter found (tried: python3.11, python3, python)" >&2
            exit 2
          fi
          $PYTHON scripts/check_schema_coverage.py \
            --fail-under 0 \
            --required-path combat_state.rewards_processed \
            --required-path encounter_state.encounter_completed \
            --required-path encounter_state.encounter_summary \
            --required-path encounter_state.rewards_processed \
            --required-path rewards_pending.processed \
            --required-path rewards_pending.level_up_available \
            --required-path custom_campaign_state.level_up_pending \
            --required-path custom_campaign_state.level_up_in_progress \
            --required-path custom_campaign_state.last_location \
            --required-path custom_campaign_state.last_story_mode_sequence_id \
            --required-path custom_campaign_state.budget_warnings_shown \
            --required-path custom_campaign_state.player_character_data_extras \
            --required-path world_events \
            --required-path faction_updates \
            --required-path time_events \
            --required-path rumors \
            --required-path scene_event \
            --required-path complications \
            --required-path player_character_data.equipped_items.shoulders \
            --required-path player_character_data.equipped_items.chest \
            --required-path player_character_data.equipped_items.waist \
            --required-path player_character_data.equipped_items.legs
  python-lint:
    name: Python Linting (Ruff)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Install Ruff
        run: |
          PYTHON=$(command -v python3.11 || command -v python3 || command -v python || true)
          if [ -z "$PYTHON" ]; then
            echo "::error::No suitable Python interpreter found (tried: python3.11, python3, python)" >&2
            exit 2
          fi
          $PYTHON -m venv --clear .venv-ruff
          .venv-ruff/bin/pip install --upgrade pip
          .venv-ruff/bin/pip install ruff==0.8.4

      - name: Run Ruff linter
        run: |
          # Non-blocking for incremental adoption - shows errors but doesn't fail CI
          .venv-ruff/bin/ruff check . --output-format=github || true

      - name: Run Ruff formatter check
        run: |
          # Non-blocking for incremental adoption
          .venv-ruff/bin/ruff format --check . || true

  # Python type checking with mypy
  python-typecheck:
    name: Python Type Checking (mypy)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Repair workspace permissions for checkout
        run: |
          if [ -d "$GITHUB_WORKSPACE" ]; then
            chmod -R u+rwX "$GITHUB_WORKSPACE" || true
          fi

      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Install dependencies
        run: |
          PYTHON=$(command -v python3.11 || command -v python3 || command -v python || true)
          if [ -z "$PYTHON" ]; then
            echo "::error::No suitable Python interpreter found (tried: python3.11, python3, python)" >&2
            exit 2
          fi
          $PYTHON -m venv --clear .venv-mypy
          .venv-mypy/bin/pip install --upgrade pip
          # Install mypy with pinned version
          .venv-mypy/bin/pip install mypy==1.13.0
          # Install project dependencies for type checking
          if [ -f requirements.txt ]; then .venv-mypy/bin/pip install -r requirements.txt; fi
          if [ -f mvp_site/requirements.txt ]; then .venv-mypy/bin/pip install -r mvp_site/requirements.txt; fi

      - name: Run mypy type checker
        run: |
          # Run mypy on the main code directories
          # Non-blocking for incremental adoption - shows errors but doesn't fail CI
          .venv-mypy/bin/mypy mvp_site/ --config-file mvp_site/mypy.ini --no-error-summary || true

  # JavaScript linting with ESLint
  javascript-lint:
    name: JavaScript Linting (ESLint)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8  # v4.0.2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          # ESLint installed via npm ci from package.json
          # Lints both .js and .mjs files (ES modules)
          # Non-blocking for incremental adoption - shows errors but doesn't fail CI
          npx eslint . --ext .js,.mjs || true
