# ⚠️ EXAMPLE WORKFLOW - REQUIRES INTEGRATION
# This workflow was exported from a working project and serves as an EXAMPLE ONLY.
# You MUST adapt the following before using:
# - $GCP_PROJECT_ID → Your Google Cloud project ID
# - $GITHUB_REPOSITORY → Your repository (owner/repo)
# - $GITHUB_OWNER → Your GitHub username or org
# - Service account configurations and secrets
# - Environment-specific variables and paths
#
# See workflows/README.md for integration instructions.
# ---

name: Self-Hosted MVP Shards

on:
  push:
    branches: [main, dev]
  pull_request:
    paths:
      - "mvp_site/**"
      - "tests/**"
      - "run_tests.sh"
      - "scripts/pr_autonomy_metrics.py"
      - "scripts/trace_to_eval_case.py"
      - "scripts/validate_prompt_tool_contracts.py"
      - "scripts/venv_utils.sh"
      - "mvp_site/schemas/prompt_tool_contracts.json"
      - ".github/workflows/self-hosted-mvp-shard1.yml"
  workflow_dispatch:

concurrency:
  group: self-hosted-mvp-shards-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write
  pull-requests: read

jobs:
  harness-autonomy-self-hosted:
    name: Harness autonomy checks (self hosted)
    # Never run untrusted fork PR code on self-hosted infrastructure.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    runs-on: ${{ fromJson(vars.SELF_HOSTED_RUNNER_LABELS || '["self-hosted"]') }}
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1 # v4.1.1

    - name: Run harness autonomy checks (self-hosted)
      env:
        GH_TOKEN: ${{ github.token }}
        GITHUB_ACTIONS: "true"
      run: |
        cat <<'EOF' >/tmp/run-harness-autonomy-self-hosted.sh
        #!/usr/bin/env bash
        set -euo pipefail
        source scripts/venv_utils.sh
        ensure_venv
        ensure_requirements_installed

        python -m pytest \
          tests/scripts/test_pr_autonomy_metrics.py \
          tests/scripts/test_trace_to_eval_case.py \
          tests/scripts/test_validate_prompt_tool_contracts.py

        python scripts/validate_prompt_tool_contracts.py

        python scripts/pr_autonomy_metrics.py \
          --repo "${{ github.repository }}" \
          --limit 20 \
          --prompt-source claude_local_strict \
          --no-persist \
          --output-json /tmp/harness_metrics_ci.json
        EOF

        chmod +x /tmp/run-harness-autonomy-self-hosted.sh
        ./self-hosted-runner/run-in-ci-container.sh \
          --workspace "$GITHUB_WORKSPACE" \
          --cmd-file /tmp/run-harness-autonomy-self-hosted.sh

    - name: Upload harness autonomy artifacts
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: harness-autonomy-self-hosted
        path: /tmp/harness_metrics_ci.json
        retention-days: 30
        if-no-files-found: ignore

  mvp-shard-1:
    name: Directory tests (core-mvp-1(self hosted))
    # Never run untrusted fork PR code on self-hosted infrastructure.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    runs-on: ${{ fromJson(vars.SELF_HOSTED_RUNNER_LABELS || '["self-hosted"]') }}
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1 # v4.1.1

    - name: Runner control plane
      uses: ./.github/actions/runner-control-plane

    - name: Run core-mvp-1 tests (self-hosted)
      uses: ./.github/actions/container-run
      with:
        command: |
          set -euo pipefail
          source scripts/venv_utils.sh
          ensure_venv
          ensure_requirements_installed
          SHARD_DISPLAY=$((0 + 1))
          echo "🧩 Running Shard ${SHARD_DISPLAY} of 3 (core-mvp-1)"
          chmod +x run_tests.sh
          ./run_tests.sh --test-dirs=mvp_site --parallel --exclude-integration --exclude-mcp
      env:
        TESTING: "true"
        TESTING_AUTH_BYPASS: "true"
        MOCK_SERVICES_MODE: "true"
        FAST_TESTS: "1"
        GEMINI_API_KEY: "test-ci-key-only"
        CEREBRAS_API_KEY: "test-ci-key-only"
        OPENROUTER_API_KEY: "test-ci-key-only"
        TEST_GEMINI_API_KEY: "test-ci-key-only"
        GOOGLE_APPLICATION_CREDENTIALS: "/dev/null"
        ENABLE_SEMANTIC_ROUTING: "false"
        ENABLE_BROWSER_TESTS: "0"
        ENABLE_BUILD_TESTS: "0"
        ENABLE_NETWORK_TESTS: "0"
        GITHUB_ACTIONS: "true"
        TEST_MAX_WORKERS: 2

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: mvp-shard1-test-results
        path: mvp_site/test-results/
        retention-days: 30
        if-no-files-found: ignore

  mvp-shard-2:
    name: Directory tests (core-mvp-2(self hosted))
    # Never run untrusted fork PR code on self-hosted infrastructure.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    runs-on: ${{ fromJson(vars.SELF_HOSTED_RUNNER_LABELS || '["self-hosted"]') }}
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1 # v4.1.1

    - name: Runner control plane
      uses: ./.github/actions/runner-control-plane

    - name: Run core-mvp-2 tests (self-hosted)
      uses: ./.github/actions/container-run
      with:
        command: |
          set -euo pipefail
          source scripts/venv_utils.sh
          ensure_venv
          ensure_requirements_installed
          SHARD_DISPLAY=$((1 + 1))
          echo "🧩 Running Shard ${SHARD_DISPLAY} of 3 (core-mvp-2)"
          chmod +x run_tests.sh
          ./run_tests.sh --test-dirs=mvp_site --parallel --exclude-integration --exclude-mcp
      env:
        TESTING: "true"
        TESTING_AUTH_BYPASS: "true"
        MOCK_SERVICES_MODE: "true"
        FAST_TESTS: "1"
        GEMINI_API_KEY: "test-ci-key-only"
        CEREBRAS_API_KEY: "test-ci-key-only"
        OPENROUTER_API_KEY: "test-ci-key-only"
        TEST_GEMINI_API_KEY: "test-ci-key-only"
        GOOGLE_APPLICATION_CREDENTIALS: "/dev/null"
        ENABLE_SEMANTIC_ROUTING: "false"
        ENABLE_BROWSER_TESTS: "0"
        ENABLE_BUILD_TESTS: "0"
        ENABLE_NETWORK_TESTS: "0"
        GITHUB_ACTIONS: "true"
        TEST_MAX_WORKERS: 2

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: mvp-shard2-test-results
        path: mvp_site/test-results/
        retention-days: 30
        if-no-files-found: ignore

  mvp-shard-3:
    name: Directory tests (core-mvp-3(self hosted))
    # Never run untrusted fork PR code on self-hosted infrastructure.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    runs-on: ${{ fromJson(vars.SELF_HOSTED_RUNNER_LABELS || '["self-hosted"]') }}
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1 # v4.1.1

    - name: Runner control plane
      uses: ./.github/actions/runner-control-plane

    - name: Run core-mvp-3 tests (self-hosted)
      uses: ./.github/actions/container-run
      with:
        command: |
          set -euo pipefail
          source scripts/venv_utils.sh
          ensure_venv
          ensure_requirements_installed
          SHARD_DISPLAY=$((2 + 1))
          echo "🧩 Running Shard ${SHARD_DISPLAY} of 3 (core-mvp-3)"
          chmod +x run_tests.sh
          ./run_tests.sh --test-dirs=mvp_site --parallel --exclude-integration --exclude-mcp
      env:
        TESTING: "true"
        TESTING_AUTH_BYPASS: "true"
        MOCK_SERVICES_MODE: "true"
        FAST_TESTS: "1"
        GEMINI_API_KEY: "test-ci-key-only"
        CEREBRAS_API_KEY: "test-ci-key-only"
        OPENROUTER_API_KEY: "test-ci-key-only"
        TEST_GEMINI_API_KEY: "test-ci-key-only"
        GOOGLE_APPLICATION_CREDENTIALS: "/dev/null"
        ENABLE_SEMANTIC_ROUTING: "false"
        ENABLE_BROWSER_TESTS: "0"
        ENABLE_BUILD_TESTS: "0"
        ENABLE_NETWORK_TESTS: "0"
        GITHUB_ACTIONS: "true"
        TEST_MAX_WORKERS: 2

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: mvp-shard3-test-results
        path: mvp_site/test-results/
        retention-days: 30
        if-no-files-found: ignore
