#!/bin/bash
# restore_crontab.sh - Restore standard jleechanorg automation crontab entries
#
# This script restores the standard cron jobs for the jleechanorg automation system:
# 1. PR monitoring (hourly)
# 2. Codex GitHub Mentions automation (hourly at :15)
# 3. PR fixing with orchestration (every 30 minutes)
# 4. Claude conversations backup (every 4 hours)
#
# Usage:
#   ./restore_crontab.sh                 # Interactive mode (prompts before restore)
#   ./restore_crontab.sh --force         # Force restore without prompts
#   ./restore_crontab.sh --dry-run       # Show what would be restored without applying

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Detect if running in dry-run or force mode
DRY_RUN=false
FORCE=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo -e "${BLUE}📋 DRY RUN MODE - No changes will be made${NC}\n"
elif [[ "${1:-}" == "--force" ]]; then
    FORCE=true
    echo -e "${YELLOW}⚡ FORCE MODE - Skipping confirmation prompts${NC}\n"
fi


# Verify GITHUB_TOKEN is set
if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    echo -e "${RED}❌ ERROR: GITHUB_TOKEN environment variable is not set${NC}"
    echo -e "   Export your GitHub token before running this script:"
    echo -e "   ${BLUE}export GITHUB_TOKEN='ghp_xxxxxxxxxxxx'${NC}"
    exit 1
fi

# Create logs directory if it doesn't exist (cross-platform)
if [[ "$(uname)" == "Darwin" ]]; then
    LOG_DIR="$HOME/Library/Logs/worldarchitect-automation"
else
    LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/worldarchitect-automation/logs"
fi
if [[ ! -d "$LOG_DIR" ]] && [[ "$DRY_RUN" == "false" ]]; then
    echo -e "${BLUE}📁 Creating log directory: $LOG_DIR${NC}"
    mkdir -p "$LOG_DIR"
fi

# Backup current crontab
BACKUP_FILE="$HOME/.crontab_backup_$(date +%Y%m%d_%H%M%S)"
if [[ "$DRY_RUN" == "false" ]]; then
    echo -e "${BLUE}💾 Backing up current crontab to: $BACKUP_FILE${NC}"
    crontab -l > "$BACKUP_FILE" 2>/dev/null || echo "# No existing crontab" > "$BACKUP_FILE"
    echo -e "${GREEN}✅ Backup saved${NC}\n"
else
    echo -e "${BLUE}💾 Would backup current crontab to: $BACKUP_FILE${NC}\n"
fi

# Standard crontab template
read -r -d '' CRONTAB_TEMPLATE << 'EOF' || true
# jleechanorg Automation System - Standard Cron Jobs
# Generated by restore_crontab.sh on $(date +"%Y-%m-%d %H:%M:%S")
#
# NOTE: Ensure GITHUB_TOKEN is exported in your shell profile
# Add to ~/.zshrc or ~/.bash_profile:
#   export GITHUB_TOKEN="ghp_xxxxxxxxxxxx"

# Set PATH to include local binaries
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin

# Workflow 1: PR monitoring (comment-only mode) - Every hour
# Posts @codex automation comments on PRs with new commits
0 * * * * jleechanorg-pr-monitor >> $HOME/Library/Logs/worldarchitect-automation/jleechanorg_pr_monitor.log 2>&1

# Workflow 3: Codex GitHub Mentions automation - Every hour at :15
# Processes Codex tasks queue via browser automation (clicks "Update branch" buttons)
# NOTE: Requires Chrome with CDP on port 9222 (see README.md for setup)
15 * * * * jleechanorg-pr-monitor --codex-update >> $HOME/Library/Logs/worldarchitect-automation/codex_automation.log 2>&1

# Workflow 2: Orchestrated PR fixes - Every 30 minutes
# Autonomously fixes merge conflicts and failing CI checks using Gemini agents
*/30 * * * * jleechanorg-pr-monitor --fixpr --max-prs 5 --fixpr-agent gemini >> $HOME/Library/Logs/worldarchitect-automation/jleechanorg_pr_monitor.log 2>&1

# Claude conversations backup - Every 4 hours
# Backs up Claude Code conversations to Dropbox
0 */4 * * * "$HOME/.local/bin/claude_backup_cron.sh" "$HOME/Library/CloudStorage/Dropbox" 2>&1

EOF

# Show what will be restored
echo -e "${BLUE}📝 Crontab entries to be restored:${NC}"
echo -e "${YELLOW}──────────────────────────────────────────────────────────────${NC}"
echo "$CRONTAB_TEMPLATE" | sed "s/\$(date +\"%Y-%m-%d %H:%M:%S\")/$(date +"%Y-%m-%d %H:%M:%S")/g"
echo -e "${YELLOW}──────────────────────────────────────────────────────────────${NC}\n"

# Confirm before proceeding (unless --force or --dry-run)
if [[ "$DRY_RUN" == "false" ]] && [[ "$FORCE" == "false" ]]; then
    echo -e "${YELLOW}⚠️  This will replace your current crontab with the standard automation jobs.${NC}"
    echo -e "   Your existing crontab has been backed up to: $BACKUP_FILE"
    echo ""
    read -p "Do you want to proceed? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${RED}❌ Aborted by user${NC}"
        exit 1
    fi
fi

# Apply the new crontab
if [[ "$DRY_RUN" == "false" ]]; then
    echo -e "${BLUE}🔧 Installing crontab entries...${NC}"
    # Expand $HOME since crontab doesn't support shell variable expansion
    echo "$CRONTAB_TEMPLATE" | \
        sed "s/\$(date +\"%Y-%m-%d %H:%M:%S\")/$(date +"%Y-%m-%d %H:%M:%S")/g" | \
        sed "s|\$HOME|$HOME|g" | \
        crontab -
    echo -e "${GREEN}✅ Crontab restored successfully!${NC}\n"
else
    echo -e "${BLUE}🔧 DRY RUN: Would install crontab entries${NC}\n"
fi

# Verification
echo -e "${BLUE}🔍 Verification Commands:${NC}"
echo -e "   View current crontab:    ${GREEN}crontab -l${NC}"
echo -e "   Check logs directory:    ${GREEN}ls -lh $LOG_DIR${NC}"
echo -e "   Test PR monitor:         ${GREEN}jleechanorg-pr-monitor --dry-run${NC}"
echo -e "   Check safety status:     ${GREEN}automation-safety-cli status${NC}"
echo ""

# Check if jleechanorg-pr-monitor is installed
if ! command -v jleechanorg-pr-monitor &> /dev/null; then
    echo -e "${YELLOW}⚠️  WARNING: jleechanorg-pr-monitor command not found${NC}"
    echo -e "   Install the package with: ${BLUE}pip install jleechanorg-pr-automation${NC}"
    echo -e "   Or from source:          ${BLUE}cd automation && pip install -e .${NC}"
    echo ""
fi

# Check if GITHUB_TOKEN is available to cron
echo -e "${BLUE}🔑 GitHub Token Configuration:${NC}"
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
    echo -e "${GREEN}✅ GITHUB_TOKEN is set in current shell${NC}"
    echo -e "   To make it available to cron jobs, add this to ~/.zshrc or ~/.bash_profile:"
    echo -e "   ${BLUE}export GITHUB_TOKEN='${GITHUB_TOKEN:0:7}...'${NC}"
else
    echo -e "${RED}❌ GITHUB_TOKEN is not set${NC}"
fi
echo ""

# Chrome CDP check for Codex automation
echo -e "${BLUE}🌐 Chrome CDP Configuration (for Codex automation):${NC}"
if curl -s http://localhost:9222/json/version &> /dev/null; then
    echo -e "${GREEN}✅ Chrome is running with remote debugging on port 9222${NC}"
    CHROME_VERSION=$(curl -s http://localhost:9222/json/version | grep -o '"Browser":"[^"]*"' | cut -d'"' -f4)
    echo -e "   Version: ${BLUE}$CHROME_VERSION${NC}"
else
    echo -e "${YELLOW}⚠️  Chrome is not running with remote debugging${NC}"
    echo -e "   The Codex automation requires Chrome with CDP enabled."
    echo -e "   See ${BLUE}automation/README.md${NC} Workflow 3 for setup instructions."
fi
echo ""

# Summary
if [[ "$DRY_RUN" == "false" ]]; then
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}✅ Crontab restore complete!${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e ""
    echo -e "Next steps:"
    echo -e "  1. Verify crontab:     ${BLUE}crontab -l${NC}"
    echo -e "  2. Check logs:         ${BLUE}tail -f $LOG_DIR/jleechanorg_pr_monitor.log${NC}"
    echo -e "  3. Test manually:      ${BLUE}jleechanorg-pr-monitor --dry-run${NC}"
    echo -e ""
    echo -e "Backup location: ${BLUE}$BACKUP_FILE${NC}"
else
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}DRY RUN COMPLETE - No changes were made${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
fi
