"""Generated by browserclaw — WorldAI API client.
   Auth: Firebase Bearer token from firebase.auth().currentUser.getIdToken()
   Base: https://mvp-site-app-dev-i6xf2p72ka-uc.a.run.app
"""

import requests


class WorldAIClient:
    """Auto-generated Python client for WorldAI REST API."""

    def __init__(self, firebase_token: str, session: requests.Session | None = None):
        self.base = "https://mvp-site-app-dev-i6xf2p72ka-uc.a.run.app"
        self.session = session or requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {firebase_token}",
            "Content-Type": "application/json",
        })

    # ─── No auth required ────────────────────────────────────────────────────────

    def server_time(self) -> dict:
        """GET /api/time — server timestamp"""
        r = self.session.get(f"{self.base}/api/time")
        r.raise_for_status()
        return r.json()

    # ─── Auth required ───────────────────────────────────────────────────────────

    def settings(self) -> dict:
        """GET /api/settings — LLM provider config"""
        r = self.session.get(f"{self.base}/api/settings")
        r.raise_for_status()
        return r.json()

    def list_campaigns(self) -> list[dict]:
        """GET /api/campaigns — list all user campaigns"""
        r = self.session.get(f"{self.base}/api/campaigns")
        r.raise_for_status()
        return r.json()

    def get_campaign(self, campaign_id: str, story_limit: int = 300) -> dict:
        """GET /api/campaigns/{id} — full campaign detail"""
        r = self.session.get(
            f"{self.base}/api/campaigns/{campaign_id}",
            params={"story_limit": story_limit},
        )
        r.raise_for_status()
        return r.json()

    def get_story(self, campaign_id: str, story_limit: int = 100) -> dict:
        """GET /api/campaigns/{id}/story — paginated story only"""
        r = self.session.get(
            f"{self.base}/api/campaigns/{campaign_id}/story",
            params={"story_limit": story_limit},
        )
        r.raise_for_status()
        return r.json()

    def export_campaign(self, campaign_id: str) -> str:
        """GET /api/campaigns/{id}/export — formatted text export"""
        r = self.session.get(f"{self.base}/api/campaigns/{campaign_id}/export")
        r.raise_for_status()
        return r.text

    def send_interaction(
        self,
        campaign_id: str,
        user_input: str,
        mode: str = "god",
        stream: bool = False,
    ) -> dict:
        """POST /api/campaigns/{id}/interaction — non-streaming"""
        r = self.session.post(
            f"{self.base}/api/campaigns/{campaign_id}/interaction",
            json={"user_input": user_input, "mode": mode, "stream": stream},
        )
        r.raise_for_status()
        return r.json()

    def stream_interaction(
        self,
        campaign_id: str,
        user_input: str,
        mode: str = "god",
    ):
        """POST /api/campaigns/{id}/interaction?stream=true — SSE streaming.
           Returns the raw requests.Response for streaming consumption.
        """
        return self.session.post(
            f"{self.base}/api/campaigns/{campaign_id}/interaction?stream=true",
            json={"user_input": user_input, "mode": mode},
            stream=True,
        )


# ─── Quick test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python generated_client.py <firebase_id_token>")
        sys.exit(1)

    client = WorldAIClient(sys.argv[1])

    # Quick sanity checks
    print("server_time:", client.server_time()["server_timestamp"])
    print("settings:", client.settings()["llm_provider"])
    print("campaigns:", len(client.list_campaigns()), "campaigns")
