"""Generated by browserclaw from /tmp/mvp-explore.har."""

import httpx


class BrowserClawClient:
    def __init__(self, client: httpx.Client | None = None):
        self.client = client or httpx.Client(follow_redirects=True)

    def get_api_time(self):
        """Public endpoint - returns server timestamp. No auth needed."""
        url = "https://mvp-site-app-dev-i6xf2p72ka-uc.a.run.app/api/time".format()
        params = {}
        params = {key: value for key, value in params.items() if value is not None}
        payload = {}
        payload = {key: value for key, value in payload.items() if value is not None}
        response = self.client.request(
            "GET",
            url,
            params=params or None,
            json=payload or None,
        )
        response.raise_for_status()
        return response.json() if response.content else None


    def get_api_settings(self):
        """Returns user settings. Requires Firebase ID token: Authorization: Bearer <firebase_id_token>"""
        url = "https://mvp-site-app-dev-i6xf2p72ka-uc.a.run.app/api/settings".format()
        params = {}
        params = {key: value for key, value in params.items() if value is not None}
        payload = {}
        payload = {key: value for key, value in payload.items() if value is not None}
        response = self.client.request(
            "GET",
            url,
            params=params or None,
            json=payload or None,
        )
        response.raise_for_status()
        return response.json() if response.content else None


    def get_api_campaigns(self):
        """Returns user's D&D campaigns. Requires Firebase ID token."""
        url = "https://mvp-site-app-dev-i6xf2p72ka-uc.a.run.app/api/campaigns".format()
        params = {}
        params = {key: value for key, value in params.items() if value is not None}
        payload = {}
        payload = {key: value for key, value in payload.items() if value is not None}
        response = self.client.request(
            "GET",
            url,
            params=params or None,
            json=payload or None,
        )
        response.raise_for_status()
        return response.json() if response.content else None


    def get_api_constants_models(self):
        """Returns LLM model constants/availability. Requires Firebase ID token."""
        url = "https://mvp-site-app-dev-i6xf2p72ka-uc.a.run.app/api/constants/models".format()
        params = {}
        params = {key: value for key, value in params.items() if value is not None}
        payload = {}
        payload = {key: value for key, value in payload.items() if value is not None}
        response = self.client.request(
            "GET",
            url,
            params=params or None,
            json=payload or None,
        )
        response.raise_for_status()
        return response.json() if response.content else None
